### ISSUE TITLE
Add useful og:description

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/WhoCanIVoteFor#101]
1. Candidate's statement if we have it
2. Wikipedia URL
3. Last known candidacy

**Comment by jf1** [comment]
On the homepage, add "including information about all candidates standing in the 2017 General Election" be appended to the content in: <meta property="og:description" content="Find out about elections, candidates and polling stations with Democracy Club's WhoCanIVoteFor tool." />

So it becomes:
`<meta property="og:description" content="Find out about elections, candidates and polling stations with Democracy Club's WhoCanIVoteFor tool, including information about all candidates standing in the 2017 General Election." />`

**Comment by annapowellsmith** [comment]
See also #149 and #159

**Comment by annapowellsmith** [comment]
Fixed with #149
