### ISSUE TITLE
Past referendums on WCIVF

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/WhoCanIVoteFor#1038]
https://whocanivotefor.co.uk/elections/ref.croydon.2021-10-07/croydon-governance-referendum/

![Screenshot 2022-02-07 103426](https://user-images.githubusercontent.com/61510609/152771730-32f2c27a-df7f-49e8-977f-f30069a4e700.png)

The action here is to keep the question but change the text to past tense.

**This referendum was held on [date]**

**the question on the ballot paper was: 
[question]**

See also: https://github.com/DemocracyClub/WhoCanIVoteFor/issues/690

**Comment by michaeljcollinsuk** [comment]
This was related to the move to new deployment/infra setup. I've added the referendum details, via running the "add_referendum" management command via Lambda using the AWS console. I've also stored this as an event template so that in future it is easy to amend when we want to add new referendums.
