### ISSUE TITLE
Double General Election via 'All Elections' route 🐛

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/WhoCanIVoteFor#105]
For any GE2017 elections in the [All elections menu](https://whocanivotefor.co.uk/elections/), I don't see any results. e.g. https://whocanivotefor.co.uk/elections/parl.grantham-and-stamford.2017-06-08/grantham-and-stamford. 

The postcode lookup is working normally.

Not super urgent!

**Comment by JoeMitchell** [comment]
Relatedly, it's not displaying the name of the next election... I'm guessing this is an Every Election thing rather than a Who thing, but will leave here in case.

![image](https://cloud.githubusercontent.com/assets/8096305/25888749/3d411fc6-355f-11e7-9759-2cb6c56dccbc.png)

**Comment by symroe** [comment]
I think this was an initial import error. Fixed now either way
