### ISSUE TITLE
Add donate link to the feedback form

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/WhoCanIVoteFor#107]
![image](https://cloud.githubusercontent.com/assets/8096305/25948046/e0d18e7e-3649-11e7-9bd6-1afd593cdaa6.png)

I realise it might be tricky, cos, at the moment, tapping `Yes` or `No` has the same effect.

But would be lovely if a user tapped `Yes` and 

>Great! Can you chip in a donation to keep this site running? Or tell us anything more. 

Actually, if they tap `No` it should say

>We're sorry! Please add more details below and help us improve faster with a donation.

In both those cases, I'm imagining that `donation` is a link. But it could be a button alongside `Send feedback`

**Comment by JoeMitchell** [comment]
@symroe Had some more thoughts on this. Perhaps, e.g., it should actually open in a new page with a range of asks, including 'Help get information'.

I think the MVP improvement of this is just adding a donate link — then we could review again!

**Comment by symroe** [comment]
First attempt done!
