### ISSUE TITLE
Import and present previous party affiliation from YNR

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/WhoCanIVoteFor#1077]
Once DemocracyClub/yournextrepresentative#1770 is deployed we need to import the data in the WCIVF.

This should copy the model on YNR:

- [x] Add a column to the `PersonPost` model
- [ ] Present the information on the front end where it exists
- [x] Add the field to the API so that devs.DC can import it

**Comment by VirginiaDooley** [comment]
Closed with https://github.com/DemocracyClub/WhoCanIVoteFor/pull/1126
