### ISSUE TITLE
Incoherent text on constituency and post page(s)

### ISSUE THREAD

**Issue by jf1** [DemocracyClub/WhoCanIVoteFor#108]
Raised by [@Huw2 on Slack](https://democracyclub.slack.com/archives/C02Q1MV53/p1494398939087290), re the text used on a [constituency page](https://whocanivotefor.co.uk/elections/parl.brigg-and-goole.2017-06-08/brigg-and-goole)
![image](https://cloud.githubusercontent.com/assets/4711363/26009361/6565b4de-3740-11e7-8356-eae0abc9c834.png)

Ideally the breadcrumbs would be:
Home / Elections / 2017 General Election / Brigg and Goole

And the text would be:
The **UK General Election** will be held on **8 Jun 2017**
Then:
Candidates for **Brigg and Goole**
Then the list of expected or confirmed candidates.

Local elections are handled better, eg (from [here](https://whocanivotefor.co.uk/elections/local.peterborough.2017-06-08/peterborough-local-election) then [here](https://whocanivotefor.co.uk/elections/local.peterborough.2017-06-08/post-UTW:E05010809/east)):
![image](https://cloud.githubusercontent.com/assets/4711363/26009788/387bea7c-3742-11e7-9cdf-10bff4931003.png)
The display above is fine, however...
![image](https://cloud.githubusercontent.com/assets/4711363/26010152/b0ccb014-3743-11e7-9850-5e9354e4a35d.png)
East is a **Ward** not a post (and AIUI there may be several posts available in a ward).
WhoCIVF shouldn't repeat **election** if it's consistently in every election's text descriptor.
I still believe DC/EE should use the LA's official name from the registry (in this case: Peterborough City Council), as raised in https://github.com/DemocracyClub/yournextrepresentative/issues/67
This would give:
East is a Ward in the Peterborough City Council election.
Ideally this would be appended with:
One post is available.
Then the list of expected or confirmed candidates.

**Comment by jf1** [comment]
I should've read more Slack messages - the text is fine [here](https://whocanivotefor.co.uk/elections/parl.2017-06-08/post-WMC:E14000596/brigg-and-goole) and candidates are displayed there too.

Joe started https://github.com/DemocracyClub/WhoCanIVoteFor/issues/105 which highlights there are two different paths to GE17 pages on WhoCIVF. One route leads you a working page while the other leads to a faulty page such as the one at the top of this issue.

The sorting of /elections isn't human-friendly so I've started https://github.com/DemocracyClub/WhoCanIVoteFor/issues/109

The problem of "East is a post in the Peterborough local election election" remains so I'll leave this issue open.

**Comment by annapowellsmith** [comment]
Breadcrumbs and intro text on constituency pages now fixed. 

"Local election election" now fixed (but see #157).

Closing this, but feel free to make a new issue for "wards" vs "posts"!
