### ISSUE TITLE
Entering candidate birth date as 1962-03 gives  "Server Error (500)"

### ISSUE THREAD

**Issue by EdwardBetts** [DemocracyClub/WhoCanIVoteFor#111]
I tried adding a candidate birth date as 1962-03, the site returned "Server Error (500)"

**Comment by andylolz** [comment]
Oops I think this issue lives on https://github.com/DemocracyClub/yournextrepresentative

**Comment by EdwardBetts** [comment]
Thanks.

**Comment by andylolz** [comment]
In fact, I suspect it’s a duplicate of https://github.com/mysociety/yournextrepresentative/issues/907
