### ISSUE TITLE
Candidate photo not fetched from YNR

### ISSUE THREAD

**Issue by VirginiaDooley** [DemocracyClub/WhoCanIVoteFor#1127]
### Issue and Steps to Reproduce
Reported by a user on Slack: 
> Is there a reason the photo I can see for this candidate in the [candidates](https://candidates.democracyclub.org.uk/person/84574/neil-reynolds) site isn't appearing in [wcivf](https://whocanivotefor.co.uk/person/84574/neil-reynolds)?

### Additional Details
* Browser and version
* Were you logged in?

**Comment by milh0use** [comment]
In case it's relevant, there was a photo already, I wanted to replace it with a better one the local party sent me, but I didn't notice how huge the photo was. I resized the photos I uploaded later and they worked fine. In case you want to reproduce the issue, I'm on slightly flaky satellite broadband in rural Texas! The upload took a while without any obvious feedback that it was uploading and I managed to upload it twice, at least one instance of which was rejected as a duplicate. Other than that, I can't think of anything peculiar about it.

**Comment by VirginiaDooley** [comment]
Thanks this is helpful. This has now been resolved at the database level so you should now be able to see the photo. 

"without any obvious feedback that it was uploading" - I think this is something we can look at improving. 

> In case it's relevant, there was a photo already, I wanted to replace it with a better one the local party sent me, but I didn't notice how huge the photo was. I resized the photos I uploaded later and they worked fine. In case you want to reproduce the issue, I'm on slightly flaky satellite broadband in rural Texas! The upload took a while without any obvious feedback that it was uploading and I managed to upload it twice, at least one instance of which was rejected as a duplicate. Other than that, I can't think of anything peculiar about it.
