### ISSUE TITLE
Make entire 'candidate card' on postcode page the link

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/WhoCanIVoteFor#120]
I agree with David

![image](https://cloud.githubusercontent.com/assets/8096305/26213051/84a6b952-3bef-11e7-96a7-f868da983d3c.png)

**Comment by annapowellsmith** [comment]
Fixed in https://github.com/DemocracyClub/WhoCanIVoteFor/commit/03b4619f32fbb29b89a459010b8831721054bd39
