### ISSUE TITLE
Change candidate email to ask candidates to fill in the blanks themselves!

### ISSUE THREAD

**Issue by andylolz** [DemocracyClub/WhoCanIVoteFor#121]
I.e. here:
https://github.com/DemocracyClub/WhoCanIVoteFor/blob/d9dde8d7/wcivf/apps/people/templates/people/_person_email_form.html#L58

The wording is maybe more appropriate for candidates.dc, since it assumes the sender has some knowledge of how to make the requisite changes. Over here on WCIVF, we’d probably rather just ask the candidate to do the work (possibly with some instructions included in the email??)

/cc @gerv

**Comment by gerv** [comment]
Do you have a page on YNR which is specifically for candidates or their representatives to take them through the process of updating their own record? If not, perhaps we need that...
