### ISSUE TITLE
[If they send us data in time] Add educational background to candidates

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/WhoCanIVoteFor#123]
We've been offered candidate educational background as an open dataset, but it's under embargo until Monday. I've asked for a preview of the data ASAP so we have time to get it in for a joint publication.

As soon as we get this data it should be the highest priority, as there is the chance of some high profile press around it.

The tasks here will be:

* [ ] (data depending) add YNR IDs to their data (they didn't use our list but might have done this already)
* [ ] Add a 'education' app with an importer from their CSV
* [ ] Show on the person profile in a card (order TBC, high up I think, like a CV)

**Comment by symroe** [comment]
Update: 
They have a CSV file with the following headings:

* Current Holder
* Margin
* Name
* Gender
* Date of birth
* Place of birth
* Party
* Constituency
* Region
* Country
* Sitting MP
* Since
* Gap in term
* Secondary school
* University BA
* Field
* STEM
* University Post-graduate
* Field
* STEM?
* Merged STEM:
* Clean Field
* Last job/current job
* Ethnic Minority
* Previously worked in parliament

They also don't plan on updating the data after publication. I expect we will get a number of requests to add to this data, so we should put their CSV in a Google Sheet that's editable by some trusted admins (people in the Slack).

Before doing that we should add YNR IDs to their data. I think this is best done on `(party, constituency)`, falling back to names and then manual fixups for those we can't match.

The importer should Assume a valid YNR_ID and update directly from the Google Sheet (using the 'publish as CSV' feature). This will allow us to edit the data easily. 

We might not want to display all the fields. For example, I'm not sure why we would want to show 'place of birth' – this feels like something that's more useful for committing fraud than deciding who to vote for.

**Comment by annapowellsmith** [comment]
Nesta have [published the data now](http://www.nesta.org.uk/blog/open-data-set-who-are-2017-general-elections-candidates). No specific licence, but repeated assertions that it is "open data", so I figure we're ok to use it.
