### ISSUE TITLE
Add 'report a problem with this page' button

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/WhoCanIVoteFor#1246]
This is super useful on WDIV, as people use it for bug reports they wouldn't otherwise put in the feedback form. 

I think we would catch a lot more candidates or other errors on WCIVF if we had a similar button here.

**Comment by VirginiaDooley** [comment]
For reference: https://github.com/DemocracyClub/UK-Polling-Stations/tree/49cd5c23a2187d87488ecf66e30694c8a9c47daf/polling_stations/apps/bug_reports

**Comment by VirginiaDooley** [comment]
@pmk01 Do we want this on specific pages or just in the footer?

**Comment by pmk01** [comment]
Specific pages - in the way we already do on WDIV
