### ISSUE TITLE
Issues with candidate death text

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/WhoCanIVoteFor#1257]
Election should be listed as 'countermanded', not cancelled. 

It should not appear on candidate profiles.

Why is 'this election has been cancelled...' appearing on candidate profiles? This needs to be removed.

![8ZT6IekPMs0zmWp9G3dbzaYI9I8YypSmJw](https://user-images.githubusercontent.com/61510609/173622663-7229a203-93ab-4973-9340-3411ed1d166c.jpg)

https://whocanivotefor.co.uk/elections/DH4%204UL/#election_local.sunderland.2022-06-16

**Comment by VirginiaDooley** [comment]
Closed with #1256
