### ISSUE TITLE
Translation file errors are not caught until deployment

### ISSUE THREAD

**Issue by VirginiaDooley** [DemocracyClub/WhoCanIVoteFor#1261]
Add `compilemessages` to CI to catch these during PRs

**Comment by pmk01** [comment]
Does this relate to this sort of thing? https://github.com/DemocracyClub/WhoCanIVoteFor/issues/1274

Because if so I strongly agree. If we end up adding more languages the issues/workload could get quite substantial.

**Comment by VirginiaDooley** [comment]
Closed with https://github.com/DemocracyClub/WhoCanIVoteFor/pull/1265
