### ISSUE TITLE
'About' page has a broken link to Privacy policy

### ISSUE THREAD

**Issue by robzor** [DemocracyClub/WhoCanIVoteFor#128]
The About page on WCIVF has a broken link to the Privacy Policy Page

[https://whocanivotefor.co.uk/about/](https://whocanivotefor.co.uk/about/) or [line 61 of about.html](https://github.com/DemocracyClub/WhoCanIVoteFor/blob/master/wcivf/templates/about.html#L61)

This is the only link on this page that is using Django tags, and it doesn't work. 
FWIW, it works on the Democracy Club About page, which is using `{% load django_markdown %}` but here it appears to be using `{% load markdown_deux_tags %}`

Obviously a minor thing, but thought it was worth logging!

**Comment by chris48s** [comment]
Should link to https://whocanivotefor.co.uk/privacy/

**Comment by pmk01** [comment]
Not any more, it doesn't.
