### ISSUE TITLE
"Elections" card is missing 2015 info

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/WhoCanIVoteFor#137]
![image](https://cloud.githubusercontent.com/assets/8096305/26298674/15486a40-3ed0-11e7-82d0-6d6b0efd0c8e.png)

Ditto here: https://whocanivotefor.co.uk/person/288/

Still there on candidates:

![image](https://cloud.githubusercontent.com/assets/8096305/26298719/41d6dd30-3ed0-11e7-9616-5bf158c8636c.png)

Ditto here: https://candidates.democracyclub.org.uk/person/288

**Comment by JoeMitchell** [comment]
Ah, this comment longer applies cos we've cut this card altogether... 

I think previous candidacy information should probably be on Who somewhere. Pretty low down, but still interesting.

**Comment by annapowellsmith** [comment]
Reopening this as the card is back, and this is still an issue.
