### ISSUE TITLE
Post page is showing parties and candidates

### ISSUE THREAD

**Issue by BobHarper1** [DemocracyClub/WhoCanIVoteFor#147]
Eg https://whocanivotefor.co.uk/elections/parl.2017-06-08/post-WMC:W07000049/aberavon - the [post_view](https://github.com/DemocracyClub/WhoCanIVoteFor/blob/master/wcivf/apps/elections/templates/elections/post_view.html) is showing cards for the parties as well as the candidates in the candidates list. It's also therefore counting twice as many candidates.

Should this be happening? Is it a problem with `uses_lists`?

**Comment by BobHarper1** [comment]
Note that this only occurs when following through `[All Elections](https://whocanivotefor.co.uk/elections/) > {Election} > {Post}`

When using the postcode this doesn't occur e.g. https://whocanivotefor.co.uk/elections/SA12%206YR/

**Comment by annapowellsmith** [comment]
Bumping this to the top of the priority list...

**Comment by BobHarper1** [comment]
This isn't happening anymore? At least not when I'm running the site locally.

**Comment by annapowellsmith** [comment]
It was a problem with the production database - currently being fixed 👍

**Comment by symroe** [comment]
Fixed!
