### ISSUE TITLE
Add a friendly page intro on candidate pages

### ISSUE THREAD

**Issue by annapowellsmith** [DemocracyClub/WhoCanIVoteFor#149]
I assume people are increasingly going to land on [candidate pages](https://whocanivotefor.co.uk/person/2919/david-drew) having arrived via Google.

So they won't necessarily know what the site is, and may not scroll down to see the interesting information.  

It might be friendly to have an autogenerated intro saying e.g. "David Drew is standing in the 2017 General Election in the Stroud constituency, for the Labour and Co-operative Party. Below you can find a copy of his CV, his latest Tweets, a link to his Facebook page and lots of other information. _See all the candidates in Stroud_." (this can be improved!)

**Comment by JoeMitchell** [comment]
Nice! Sort of like those company director auto-biography things ([e.g.](https://companycheck.co.uk/director/912377114/MR-SIMON-ROE/summary)).  

People going straight to /person pages was definitely true in 2015. Might be less true with Google linking directly to WCIVF homepage.

Some sites cunningly generate that text to live in the Google Search - that'd be cool:

![image](https://cloud.githubusercontent.com/assets/8096305/26361177/1cd2c6f4-3fd2-11e7-8b47-fa852b7e0a22.png)

**Comment by annapowellsmith** [comment]
Yes! Should be in meta description tag as well as page intro.

**Comment by symroe** [comment]
See also https://github.com/DemocracyClub/WhoCanIVoteFor/issues/101

**Comment by davidmiller** [comment]
Looking at the analytics, a very large % of search traffic to WCIVF is long tail searches for the name of a candidate.

Google is picking the Elections Card and using that text: 

![screen shot 2017-05-23 at 16 40 26](https://cloud.githubusercontent.com/assets/17229/26362668/9c5359da-3fd6-11e7-8c3a-d2d744e038e5.png)

Should 100% customise meta description per candidate today.
