### ISSUE TITLE
Allow customisation of companies house data

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/WhoCanIVoteFor#154]
Relying on https://raw.githubusercontent.com/EdwardBetts/companies-house/master/companies.csv has some issues:

* If the data changes breaks our importer, it cron just spews errors at me and I can't fix them (see #152)
* More seriously, if someone reports erroneous data/requests take down, we can't readily remove it ourselves

**Comment by JoeMitchell** [comment]
Oh, I just made a PR here: https://github.com/EdwardBetts/companies-house/pull/1  — that may have been not the right thing to do?
