### ISSUE TITLE
All elections should have "election" in the name

### ISSUE THREAD

**Issue by annapowellsmith** [DemocracyClub/WhoCanIVoteFor#157]
The elections in the [list of elections](https://whocanivotefor.co.uk/elections/) should all have "election" in the name, because various places expect that. 

[Here's an example](https://whocanivotefor.co.uk/elections/parl.copeland.2017-02-23/copeland) of something that looks odd as a result.

Obviously we could write code to handle names in different formats, but it's probably easier just to make sure the names are consistent (could maybe enforce a check on save).

**Comment by BobHarper1** [comment]
Just to add, though it may be obvious, "local election" and "by-election" should apply where relevant.

Most currently do but some don't eg [Copeland](https://whocanivotefor.co.uk/elections/parl.copeland.2017-02-23/copeland)

**Comment by JoeMitchell** [comment]
An up-to-date example of an odd result: 

![image](https://user-images.githubusercontent.com/8096305/36665912-c66f5d78-1ae0-11e8-8ef3-f1dc7224ad38.png)

https://whocanivotefor.co.uk/elections/M30%209AG/
