### ISSUE TITLE
Local by-election in Democracy Club DB doesn't show up on WCIV

### ISSUE THREAD

**Issue by simrun** [DemocracyClub/WhoCanIVoteFor#1621]
There is an upcoming by-election for one of the wards in Haringey borough. Data is here: https://candidates.democracyclub.org.uk/elections/local.haringey.hermitage-gardens.by.2023-06-29/ .

I'm not familiar with processes around WCIV, but I would have expected the election to show up when searching a Hermitage postcode (e.g. N4 1LU) on https://whocanivotefor.co.uk/ . The message shown is: "We don't know of any upcoming elections. There may also be parish, town or community council elections in some areas."

**Comment by VirginiaDooley** [comment]
This was an issue with our importer and deployment. It is now resolved. https://whocanivotefor.co.uk/elections/N4%201LU/

**Comment by sim-dt** [comment]
Yay :) 🥳
