### ISSUE TITLE
Superfluous 'the' on joint party pages

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/WhoCanIVoteFor#1638]
'The Bolton for Change'

We want to drop 'the' here (both in the card and the link text).

![Screenshot 2023-07-05 122453](https://github.com/DemocracyClub/WhoCanIVoteFor/assets/61510609/a9752c39-946f-49e2-bde2-b83ff456e5d3)

But we don't want to drop it from 'the Green party' https://whocanivotefor.co.uk/parties/joint-party:63-77/plaid-cymru-green-party-common-ground

Maybe the easiest fix is to revise the text so 'the' isn't necessary.

**Comment by pmk01** [comment]
Also: if a party has no emblems registered, the sentence reads: "This party currently has no alternative emblems registered with the Electoral Commission."

We should delete 'alternative'.

**Comment by Bekabyx** [comment]
Sure, I can take a look at these. Re: superfluous "the", could we just remove it altogether? Obviously it may not read as nicely for some parties, e.g. "The Labour Party" -> "Labour Party" but I feel like it's probably the easiest solution.

**Comment by pmk01** [comment]
Yes I agree! There isn't an ideal solution but that's ok!
