### ISSUE TITLE
Improve SEO for constituency pages

### ISSUE THREAD

**Issue by annapowellsmith** [DemocracyClub/WhoCanIVoteFor#167]
- [x] Nice meta description (use Google data to figure out what people are searching for)
- [x] Nice intro
- [x] - Use the word "constituency" not "post"
- [x] - Make sure they're in the sitemap
- [ ] - Link to them from other pages on the site
- [ ] - Use full constituency names in breadcrumbs

[Example](https://whocanivotefor.co.uk/elections/parl.2017-06-08/post-WMC:E14000580/bolton-west)

**Comment by chris48s** [comment]
> Use the word "constituency" not "post"

This needs to be determined based on the election type. For example, you don't want to use the word "constituency" if the relevant unit of electoral geography is a ward:

https://whocanivotefor.co.uk/elections/local.ceredigion.2017-06-08/post-UTE:W05000377/llandyfriog

similarly for other points in this card, if you intro is specific to the GE, it wants to only display on pages where the election is `parl.2017-06-08` + so on.

**Comment by annapowellsmith** [comment]
Thanks! We do this already on the candidate pages - just have a manual switch to check whether it's the GE.

**Comment by chris48s** [comment]
happy days then :D

**Comment by annapowellsmith** [comment]
Most of this is done now: updating #80 to cover breadcrumb improvements
