### ISSUE TITLE
File named "-"

### ISSUE THREAD

**Issue by semiprime** [DemocracyClub/WhoCanIVoteFor#1672]
There's a file named "-" in the root directory of the project. I *think* it may have been added in error, unless its purpose is too subtle for me.

It seems to be a csv of a few candidates, and not related to the other changes in the commit from when it was added: https://github.com/DemocracyClub/WhoCanIVoteFor/commit/0b03b8762401a834e71b7674d3874540f64463a9 (@symroe?)

(I spotted the file when executing a shell command and "*" was expanded to include a "-" which was then interpreted as a signal to take input from stdin. Took me a while to work out why the command was taking so long!)

**Comment by symroe** [comment]
You know, this file has bothered me for *years* but each time I notice it I'm doing something else and don't want to confuse things.

I will make a PR to remove it right now.
