### ISSUE TITLE
General results info is duplicated between all `PostElection` pages that share a parent election.

### ISSUE THREAD

**Issue by GeoWill** [DemocracyClub/WhoCanIVoteFor#1719]
When there are two by ballots (`PostElection` objects) on the same day for the same organisation (eg parl.tamworth.by.2023-10-19 & parl.mid-bedfordshire.by.2023-10-19) they are both pulling `electorate`, `ballot_papers_issued`, `turnout` and `spoilt_ballots` from the `Election` object (i.e. `parl.2023-10-19`). This means it is duplicated between those by elections, even though they have different information for those fields in YNR. 

I suspect the solution is to move those fields onto the `PostElection` object, but I guess there might be a reason this wasn't done originally?

**Comment by GeoWill** [comment]
https://whocanivotefor.co.uk/elections/local.haringey.2023-10-04/haringey-local-election/

**Comment by VirginiaDooley** [comment]
> When there are two by ballots (`PostElection` objects) on the same day for the same organisation (eg parl.tamworth.by.2023-10-19 & parl.mid-bedfordshire.by.2023-10-19) they are both pulling `electorate`, `ballot_papers_issued`, `turnout` and `spoilt_ballots` from the `Election` object (i.e. `parl.2023-10-19`). This means it is duplicated between those by elections, even though they have different information for those fields in YNR.
> 
> I suspect the solution is to move those fields onto the `PostElection` object, but I guess there might be a reason this wasn't done originally?

This sounds right. I don't think this was intentional. I'll work on the fix, thanks.
