### ISSUE TITLE
Ask partners if they will link to us, for SEO

### ISSUE THREAD

**Issue by annapowellsmith** [DemocracyClub/WhoCanIVoteFor#172]
Would be v good for SEO, if mysociety would e.g. link to us from TheyWorkForYou

Also the CVs site should link here

And anyone else we can think of

**Comment by JoeMitchell** [comment]
mySociety are already paying for ads under the search 'Who should I vote for' — which links to their tripartite blog post, which links to Who as well as a few others.

**Comment by pmk01** [comment]
Happily, I think we're beyond this now.
