### ISSUE TITLE
Explainers aren't updating

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/WhoCanIVoteFor#1768]
It's true!

**Comment by pmk01** [comment]
Actually, I think the problem here is that explainers are only updating when a candidate is added to the ballot.

**Comment by VirginiaDooley** [comment]
@pmk01 Do you have an example of an explainer that wasn't updating?

**Comment by pmk01** [comment]
Any PCC, or mayoral ballot,

**Comment by pmk01** [comment]
https://whocanivotefor.co.uk/elections/pcc.devon-and-cornwall.2024-05-02/police-and-crime-commissioner-for-devon-cornwall/

**Comment by VirginiaDooley** [comment]
Fixed with https://github.com/DemocracyClub/WhoCanIVoteFor/pull/1825
