### ISSUE TITLE
Feedbacks have broken a bit

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/WhoCanIVoteFor#1775]
In the feedback admin view:

 - The first page doesn't have a 'date created' column, for some reason.
 - The most recent feedback is July 2023.
 
These problems may or may not be related

**Comment by VirginiaDooley** [comment]
This is fixed now, but I didn't ask - are we happy with this message? Reads like a CTA for something vague. 

<img width="961" alt="Screenshot 2024-03-28 at 10 16 10 AM" src="https://github.com/DemocracyClub/WhoCanIVoteFor/assets/7017118/8e2785f4-d1ce-402a-b9b7-b7aa9b3ca136">

**Comment by VirginiaDooley** [comment]
Fixed with https://github.com/DemocracyClub/WhoCanIVoteFor/pull/1803

**Comment by pmk01** [comment]
Oh, good catch, yeah. Probably cut everything after 'Thanks for your feedback!' I suspect there was a CTA there back in the dim and distant past.
