### ISSUE TITLE
Sitemap linking to wrong URL

### ISSUE THREAD

**Issue by annapowellsmith** [DemocracyClub/WhoCanIVoteFor#178]
The [sitemap URLs](https://whocanivotefor.co.uk/sitemap.xml) are linking to https://wheredoivote.co.uk

Think this probably needs to be fixed [via Django admin](https://stackoverflow.com/questions/15402622/django-sitemap-http-example-com/15402720#15402720).

**Comment by symroe** [comment]
This was me not thinking properly! I've fixed it by logging in to each server in the cluster and running:

`Site.objects.update(domain="whocanivotefor.co.uk")`

The [migration I added](https://github.com/DemocracyClub/WhoCanIVoteFor/blob/master/wcivf/apps/core/migrations/0002_auto_20170526_1448.py) will do this for future servers.

**Comment by symroe** [comment]
I think it's cached, so it might take some time to update
