### ISSUE TITLE
This statement was last updated on

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/WhoCanIVoteFor#1781]
Dates aren't pulling through on WCIVF. EG: https://whocanivotefor.co.uk/person/109119/mark-coleman

![Screenshot 2024-02-27 120832](https://github.com/DemocracyClub/WhoCanIVoteFor/assets/61510609/17d66079-8cf8-4b01-84d2-dfaecbf35753)

**Comment by VirginiaDooley** [comment]
Fixed with https://github.com/DemocracyClub/WhoCanIVoteFor/pull/1800
