### ISSUE TITLE
font-size on body not rendering in production CSS

### ISSUE THREAD

**Issue by annapowellsmith** [DemocracyClub/WhoCanIVoteFor#179]
On production in Chrome, the `font-size` of `body`is being computed as the browser default, 16px. [Production CSS](https://whocanivotefor.co.uk/static/css/styles.d4a9f9678532.css) contains a property on `body` for `font-size: calc(1.14em+0.3vw)`, but Chrome warns this is an 'invalid property value'.

<img width="173" alt="screen shot 2017-05-29 at 12 36 49" src="https://cloud.githubusercontent.com/assets/78156/26548330/85886eea-446b-11e7-81df-2db97a1ceb18.png">

It's making all the font sizes on production too small and causing design issues e.g. this unwanted scrollbar on the header image:

<img width="612" alt="screen shot 2017-05-29 at 12 28 02" src="https://cloud.githubusercontent.com/assets/78156/26548095/4f5357f0-446a-11e7-96ca-8a405128c5d3.png">

The problem is the CSS minifier stripping whitespace for production. 

I will try [this fix](https://github.com/yui/yuicompressor/issues/59#issuecomment-249556592) in the theme.

**Comment by annapowellsmith** [comment]
PR'd here: https://github.com/DemocracyClub/dc_base_theme/pull/14 (NB I don't actually know if this will work - Chrome really wants there to be whitespace around `+`, and I don't know how the minifier will react, not sure which production minifier we're using. 

If not there are some other suggested fixes towards the end of [this thread](https://github.com/yui/yuicompressor/issues/59) - extra whitespace, subtract a negative value, etc. 

If none of these fix it quickly, we might just want to skip CSS minification.

**Comment by symroe** [comment]
I think I fixed this by simplifying the header. The `calc` issue still stands, but isn't causing this problem any more.

**Comment by annapowellsmith** [comment]
I can still see it, in various browsers with caching off... @symroe were you ever able to see it?

**Comment by symroe** [comment]
Oh sorry, I forgot to add that the cached storage on prod is still serving the old version of the CSS, so it's not fixed on prod. Can you see it locally?

**Comment by annapowellsmith** [comment]
No (but I never could!). Is it possible to clear the cache?

**Comment by symroe** [comment]
Ah, cleared the cache and it seems to be fixed now?

**Comment by annapowellsmith** [comment]
Partly... :) The scrollbar on the header image has vanished (yay!) - but I'm still seeing a broken font-size property on body, in Chrome, and the font still looks too small.

**Comment by symroe** [comment]
Maybe the solution is to add a `<style>` tag to `base.html`. The compression is valuable I think, apart from stripping this space.

**Comment by annapowellsmith** [comment]
Looks fixed now! Yay 👍

**Comment by symroe** [comment]
I think this is fixed now!
