### ISSUE TITLE
"Back to [website]" feature

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/WhoCanIVoteFor#181]
Some sites that link to us would like to be able to offer a "back to X" button for their users.

We should have the ability to show a button somewhere in the design that links to a given URL. 

I suggest this is hard coded as a setting, with the referral query string (a UTM tracker, for example) and a URL to link back to.

**Comment by annapowellsmith** [comment]
I can see why sites want this, but do we really want to do this? Users already know how to use the back button...
