### ISSUE TITLE
Contextualise candidate election list

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/WhoCanIVoteFor#1819]
We often get emails requesting to add older elections.

"Please note our local elections database only goes back to 2016."

**Comment by VirginiaDooley** [comment]
Where do you want this exactly?

**Comment by pmk01** [comment]
Underneath the list perhaps?

Relatedly: we currently don't say if an election was a by-election (or give the exact date). On rare occasions this looks like we've got a double election: https://whocanivotefor.co.uk/person/90589/rajeev-sharma

**Comment by pmk01** [comment]
Or separate past elections from future ones.
