### ISSUE TITLE
2015 constituency pages should link to 2017 constituency pages

### ISSUE THREAD

**Issue by annapowellsmith** [DemocracyClub/WhoCanIVoteFor#183]
User request from slack.

[Example](https://whocanivotefor.co.uk/elections/2015/post-65685/member-of-parliament-for-brentwood-and-ongar)

**Comment by michaeljcollinsuk** [comment]
@symroe the example link is no longer valid, but I dont think this has been resolved - as if I look at for example atconstituency from the 2017 general election http://localhost:8000/elections/parl.sheffield-central.2017-06-08/sheffield-central/ there is no link to that constituency in 2019. 

So if this is something we still want to implement it should remain open

**Comment by symroe** [comment]
In YNR I have a [`get_next_ballot_for_post`](https://github.com/DemocracyClub/yournextrepresentative/blob/master/ynr/apps/candidates/models/popolo_extra.py#L80) manager method that might be useful to implement here to provide these links.
