### ISSUE TITLE
Include Facebook personal profiles on candidate pages

### ISSUE THREAD

**Issue by annapowellsmith** [DemocracyClub/WhoCanIVoteFor#186]
We include `facebook_page_url` but not `facebook_personal_url` ([code](https://github.com/DemocracyClub/WhoCanIVoteFor/blob/master/wcivf/apps/people/templates/people/person_detail.html#L124)).

Could include both, unless there's a reason we're excluding personal URLs?

**Comment by symroe** [comment]
No reason not to do this – I expect it's just an oversight!

**Comment by annapowellsmith** [comment]
See #54. I think we should always include both if they are present
