### ISSUE TITLE
Add links to WCIVF from TWFY

### ISSUE THREAD

**Issue by annapowellsmith** [DemocracyClub/WhoCanIVoteFor#193]
Splitting this out from #167 and #172 to make management easier...

If we can add links from TWFY in to WCIVF between now and June 8th, it will greatly improve SEO, and be very useful for TWFY users.

TWFY suggest that they could add a banner linking to WCIVF, pre-filled the user's postcode if known.

Ticketing this as a reminder to submit this as a pull request to TWFY.

**Comment by mrwilson** [comment]
Throwing my hat in - this would be _awesome_.

**Comment by annapowellsmith** [comment]
Mark suggests copying previous YNR banners in TWFY codebase

**Comment by BobHarper1** [comment]
Would it be possible to link vice-versa, i.e. for WCIVF candidates who have a person entry on TWFY?

**Comment by annapowellsmith** [comment]
@BobHarper done in #192 :)

**Comment by annapowellsmith** [comment]
PR'd here: https://github.com/mysociety/theyworkforyou/pull/1270 hoping for a deploy on Monday!

**Comment by annapowellsmith** [comment]
Now live on TWFY
