### ISSUE TITLE
Add hustings on candidate pages

### ISSUE THREAD

**Issue by annapowellsmith** [DemocracyClub/WhoCanIVoteFor#197]
If there's a hustings in the candidate's constituency, add details on the candidate's page.

**Comment by BobHarper1** [comment]
Hustings aren't in the db, are they - at the moment is it just the Google Sheets? If it helps, [tabletop.js](https://github.com/jsoma/tabletop) **might** make it easier (at this late stage) to get the hustings info onto the pages. But needs a way to link to the right constituency, obvs.

**Comment by annapowellsmith** [comment]
Thanks for the suggestion! I'd be a bit wary about using Google Sheets directly (I've used [flatware](https://github.com/jsoma/flatware) in the past to sit between tabletop.js and Sheets, but still). I'll just write an importer, it shouldn't take long.

**Comment by annapowellsmith** [comment]
There are hustings in the database already! That's a nice surprise 🙂
