### ISSUE TITLE
Long [party] names break icons a bit

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/WhoCanIVoteFor#199]
![screen shot 2017-05-31 at 23 38 38](https://cloud.githubusercontent.com/assets/242329/26657196/5dd12446-465a-11e7-8f77-31f2ed65f298.png)

**Comment by BobHarper1** [comment]
Related - I gather the Statement and social media icons are only to indicate that they are present? As in, I click on them they just bring me to the candidate page.

**Comment by annapowellsmith** [comment]
@BobHarper1 yes for the moment!

**Comment by annapowellsmith** [comment]
I think the only feasible way to fix this is with ellipses...

<img width="412" alt="screen shot 2017-06-02 at 19 30 55" src="https://cloud.githubusercontent.com/assets/78156/26739524/0626345e-47ca-11e7-8b24-b876f4731723.png">
