### ISSUE TITLE
Icons and text overlap if candidate name is long

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/WhoCanIVoteFor#200]
e.g:
https://whocanivotefor.co.uk/elections/NE30%201DP/

![screenshot at 2017-06-01 21 16 24](https://cloud.githubusercontent.com/assets/6025893/26698958/e5c3fb02-470f-11e7-81cb-fdb6bb21d6cd.png)

**Comment by annapowellsmith** [comment]
Curious - I don't see this in Chrome/OSX, even when the card is at its narrowest. Which browser is this in?

<img width="352" alt="screen shot 2017-06-02 at 18 13 05" src="https://cloud.githubusercontent.com/assets/78156/26736706/2fd0d13e-47bf-11e7-8eff-f3b0774fd785.png">

**Comment by chris48s** [comment]
Screenshot is from Firefox on Ubuntu 16.04
Does not reproduce in Chromium Stable.

Couldn't speak for OSX

**Comment by annapowellsmith** [comment]
Thanks! I don't see it on Firefox/OSX. The browser isn't zoomed in is it?
Keen to fix (and clearly it will be a problem in any browser for any very long name) but am reluctant to use the same fix as #199, as I don't really want to truncate candidate names.

**Comment by chris48s** [comment]
What about
Stephen Kenneth Savill Goldspink in https://whocanivotefor.co.uk/elections/parl.2017-06-08/post-WMC:E14000842/north-east-cambridgeshire
or
Andrew Aalders-Dunthorne in https://whocanivotefor.co.uk/elections/parl.2017-06-08/post-WMC:E14000946/south-suffolk

either of those give the same behaviour for you?

**Comment by annapowellsmith** [comment]
No - breaking over 2 lines is just fundamentally OK in OSX. 

Probably a difference in the way OSX and Ubuntu render the fonts - assuming your browser isn't zoomed?

**Comment by chris48s** [comment]
Not zoomed, but if its only affecting a very specific OS/browser combo this is not high-priority

**Comment by andylolz** [comment]
Broken for me on Chrome/OSX too:
![screen shot 2017-06-02 at 21 20 05](https://cloud.githubusercontent.com/assets/464193/26743351/6149c274-47d9-11e7-9556-e24d50869962.png)

**Comment by chris48s** [comment]
Based on the screenshots posted, @annapowellsmith has a font installed which me and @andylolz don't have installed.. or possibly it is the other way round?

**Comment by chris48s** [comment]
This now looks slightly differently wrong in Firefox 57+

![screenshot at 2017-12-04 11 41 59](https://user-images.githubusercontent.com/6025893/33551108-37870c62-d8e8-11e7-8eda-0c2567ed6fde.png)

Chromium stable still looks like the old Firefox style rendering:

![screenshot at 2017-12-04 11 39 37](https://user-images.githubusercontent.com/6025893/33551210-8c369264-d8e8-11e7-865e-eb64405c81ce.png)

**Comment by pmk01** [comment]
I'm closing this because we abolished icons last year. 📤
