### ISSUE TITLE
Election update email signup is broken

### ISSUE THREAD

**Issue by annapowellsmith** [DemocracyClub/WhoCanIVoteFor#204]
A 'not found' comment:
----------------
It comes up as 'internal server error's after I entered my post code for election emails

Page
----------------
https://whocanivotefor.co.uk/elections/DN35+7PE/

**Comment by annapowellsmith** [comment]
Working for me locally on master. Need to see 500 admin email for more information.

**Comment by chris48s** [comment]
jinx ;)
See https://github.com/DemocracyClub/WhoCanIVoteFor/issues/205 for detail of what is causing it

**Comment by annapowellsmith** [comment]
thanks :) closing dupe
