### ISSUE TITLE
Leaflets since May not showing?

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/WhoCanIVoteFor#208]
Several folks in the inbox/twitter are saying they uploaded leaflets, but these aren't showing on Who.

[In my area](https://whocanivotefor.co.uk/elections/BS5+0LR/), I can only see the leaflet I uploaded for the local elections (one now-parliamentary candidate was standing for mayor) — but I've added a load of parl.2017 ones over the last couple of weeks...

**Comment by annapowellsmith** [comment]
Import script was pointing at staging, not production, because when I wrote it the feed was only available on staging. Now pointing at production - will ask @symroe for a deploy and import.
