### ISSUE TITLE
Combine cards into higher-level sections

### ISSUE THREAD

**Issue by annapowellsmith** [DemocracyClub/WhoCanIVoteFor#211]
The person detail pages for GE2017 are starting to get long and bitty (which is good, means there's lots of information on there!).

I would like to combine the cards into higher-level sections as follows.

**{{ candidate }}'s policies**
- Statement
- Party manifesto
- Leaflets
- TWFY record

**About {{ candidate }}**
- Wikipedia
- CV
- Nesta biographical info (#210)
- Companies
- Past candidacies

**{{ candidate }} online**
- Tweets
- Facebook, LinkedIn, homepage, email

**Comment by annapowellsmith** [comment]
Here's how it looks...
![screencapture-localhost-8000-person-1120-jeremy-corbyn-1496817669170](https://user-images.githubusercontent.com/78156/26865506-f7867c86-4b54-11e7-90d1-700467bb1dff.png)

**Comment by JoeMitchell** [comment]
I think this is a good idea! Where would hustings go?

(Also, have we lost 2015 elections again?!)

**Comment by annapowellsmith** [comment]
Cool. Hustings get their own card - `See <name>`

Yes re 2015 elections :( See #137

**Comment by symroe** [comment]
I actually would prefer to keep one card per thing – I find this more confusing to read, like everything is jumbled together, where as the card concept keeps thing self-contained…

**Comment by annapowellsmith** [comment]
OK! I feel like these pages do need some work, but I'm not sure exactly what form it should take - maybe something to discuss with Rose. Moving this out of "in progress", but keeping it open.
