### ISSUE TITLE
invalid postcode error is a bit ugly

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/WhoCanIVoteFor#213]
This could look nicer:

![screenshot at 2017-06-06 17 06 37](https://user-images.githubusercontent.com/6025893/26839320-9632381e-4ada-11e7-9961-03e4fe6bd295.png)

**Comment by JoeMitchell** [comment]
Quite aggressive innit! Perhaps something like:

>Oops, did you mis-type the postcode? We didn't recognise it. Please try
again.

>Sorry, we're not sure that's a UK postocde. Have you entered it correctly?

**Comment by chris48s** [comment]
I was thinking more about the layout than the wording

**Comment by BobHarper1** [comment]
Is it meant to show like this https://github.com/DemocracyClub/WhoCanIVoteFor/blob/master/wcivf/templates/home.html#L17-L19 - why doesn't it?

**Comment by chris48s** [comment]
This is fixed in the latest theme so we just need to upgrade WhoCIVF to use the current theme version to fix this.

**Comment by chris48s** [comment]
Closed in #260
