### ISSUE TITLE
No next action at bottom of constituency page

### ISSUE THREAD

**Issue by tfgg** [DemocracyClub/WhoCanIVoteFor#22]
Observing over someone's shoulder, they entered their postcode fine and scrolled down the list of elections.

Once they got to the bottom they seemed a bit lost, so maybe there needs to be a CTA there, such as sharing it by email/social media.

**Comment by andylolz** [comment]
So wait, what happened? They just scrolled to the bottom? Did they click on elections / candidates?

**Comment by tfgg** [comment]
They just closed the site, they didn't click on candidates/elections. Tbh I don't think I'd think to if I didn't already know you could.

**Comment by andylolz** [comment]
Okay so I think that while this issue is probably still valid, there’s perhaps another issue here about clearer calls to action to find out more about candidates?

**Comment by tfgg** [comment]
Right, quite possibly. The candidate card design has lots of potential.

Though I'm not convinced that it means encouraging people to click through
to candidate pages. Maybe the question the user is asking is "what's
usefully actionable here?", and there's a risk that their reaction will be
"sure, but what am I meant to do?".

On 11 Apr 2016 11:57 am, "Andy Lulham" <notifications@github.com> wrote:
>
> Okay so I think that while this issue is probably still valid, there’s
perhaps another issue here about clearer calls to action to find out more
about candidates?

**Comment by JoeMitchell** [comment]
Some more options here: 

- 'Remind me to vote'  (links to SMS/email form)
- 'Have you decided who to vote for?' Yes / No (yes--> Remind me to vote; No --> 'What would help you to decide' (text form). 
- 'Help your friends and family learn about their candidates. Share this website with them.'

**Comment by pmk01** [comment]
Joe's last point is a good one to replace the election reminders email card with.
