### ISSUE TITLE
"The 2017 General Election was held on yesterday."

### ISSUE THREAD

**Issue by hugovk** [DemocracyClub/WhoCanIVoteFor#222]
Steps to reproduce:
1. Wait for an election
2. Wait until the day after
3. Visit a postcode eg. https://whocanivotefor.co.uk/elections/SW1A%200AA/

Actual result:

> The 2017 General Election was held on yesterday. 8 candidates stood in Cities of London and Westminster constituency

Expected result:

> The 2017 General Election was held yesterday. 8 candidates stood in the Cities of London and Westminster constituency.

Delete the "on" before "yesterday", add "the" before the constituency name (because it's "the X  constituency") and pop a full-stop on the end.
https://github.com/DemocracyClub/WhoCanIVoteFor/blob/3a2f8d44787ce418d9d7650cf995c2b63f4dfa78/wcivf/apps/elections/templates/elections/postcode_view.html#L55

Looks like the "on" should also be fixed here:
https://github.com/DemocracyClub/WhoCanIVoteFor/blob/0f9a8d86a93c9356b702be55cb668839647146ac/wcivf/apps/elections/templates/elections/post_view.html#L21

**Comment by michaeljcollinsuk** [comment]
Closing as has previously been resolved:

<img width="516" alt="Screenshot 2021-02-08 at 12 35 05" src="https://user-images.githubusercontent.com/15347726/107220339-218c6b80-6a0a-11eb-94f3-2e0397fc39c7.png">
