### ISSUE TITLE
It’s not totally obvious what the “Get email alerts for future elections” signup does

### ISSUE THREAD

**Issue by andylolz** [DemocracyClub/WhoCanIVoteFor#23]
The text of this card could be clearer. Is this promising to notify me this time around? I.e. will I receive an email on the morning of 5 May 2016 telling me to go and vote?

Is this promising to email me about all future elections, including by-elections? Because it probably shouldn’t promise that.

**Comment by JoeMitchell** [comment]
1. Ah, fair enough. 

2. It's like a commitment device. If we promise it, and 100k people sign up, we'll __have__ to make it happen.

**Comment by andylolz** [comment]
How about “Subscribe to receive reminders to vote”? I’d take from that that:

 * I’ll receive a reminder about current elections (which is what I want)
 * I may or may not receive reminders for future elections (though I’d assume I could unsubscribe from those, so that’s okay). I’m basically advocating for being a bit vague here, to avoid the possibility of over-promising and under-delivering.

> If we promise it, and 100k people sign up, we'll have to make it happen.

Sure, but that is best case. Worst case is you promise it and only a small number sign up.

**Comment by andylolz** [comment]
Closing because this is pretty much addressed.
