### ISSUE TITLE
'Previous elections' text going a bit awry

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/WhoCanIVoteFor#232]
For [this candidate](https://whocanivotefor.co.uk/person/8551/james-johnston), the previous elections text misses the word 'ward' at the end: 

![image](https://user-images.githubusercontent.com/8096305/30925524-0f207c18-a3aa-11e7-8b6d-af286b4f006d.png)

But the previous elections text for [this candidate](https://whocanivotefor.co.uk/person/17212/lucy-brown), who previously stood in a different ward, doesn't:

![image](https://user-images.githubusercontent.com/8096305/30925713-aed18d74-a3aa-11e7-934d-0a211f94eccc.png)

But there is a rogue 'the' in front of the constituency name re 2017 UKPGE. Fun!

**Comment by pmk01** [comment]
These text issues have now been sorted!
