### ISSUE TITLE
What should we do about elections with unlocked candidate lists?

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/WhoCanIVoteFor#233]
It's quite cool that we're giving people loads of notice about upcoming elections on Who — and maybe it doesn't matter because there are so few searches at the mo' — but we are getting strange results like this: 

![image](https://user-images.githubusercontent.com/8096305/30961384-e7fc0924-a43d-11e7-80ba-9e5e18d3f7ed.png)

'0 candidates' is technically true at the moment, but not very helpful. And if I added a joke candidate via candidates.dc now, it would show until like April or something. I vaguely remember thinking that Who should only show elections once they're locked. But maybe I've made this up.

Ideally, we'd say something like 'There's an upcoming election. The deadline for nomination as a candidate is [`electiondate minus 19 working days`]. Find out more about standing as a candidate at beacouncillor.org.' Then flip it to show candidates at the deadline.

Any thoughts?

**Comment by chris48s** [comment]
I think at this point in time (the "off-season"), the correct approach would be to only show/import candidates for locked posts, but it would be useful to get some feedback from someone more familiar with the reasons for showing candidates on posts that aren't locked as I'm fairly sure that decision was made for a reason.

**Comment by JoeMitchell** [comment]
_[Voiceover: A brief conversation over video chat followed. It was decided that the ideal situation was to tell users everything Democracy Club knew.]_

Here's my first stab at the copy for unlocked / locked.

**Unlocked:**

> [logo] Who Can I Vote For?

> London Borough of Hackney election

> The Hackney local election will be held on Thursday 3 May, 2018. 

> The candidates officially nominated for your area (Cazenove ward) will be confirmed on [DATE election minus 19 working days].

>We currently understand that the following people are seeking nomination: [Alice, Tanya]

**Locked:**

> [logo] Who Can I Vote For?

> London Borough of Hackney election

> The Hackney local election will be held on Thursday 3 May, 2018. 

>The candidates for your area (Cazenove ward) are as follows: [Jeff, Alice, Tanya, Jennifer]

(I wonder if people know what a ward is, and how or if we should include this info — but this is a start to answering the actual Issue I raised... thoughts welcome!)

**Comment by symroe** [comment]
For unlocked: is it worth adding a CTA here?

Examples:

* If you support a political party you might be able to get involved in their campaigning work. Get in touch with them to see if you can help
* We will be trying to find out as much as we can about these elections, including events and debates, candidates contact information and statements to voters. Join out mailing list to help out, or add anything you might know about there area *here*
* Would you like to stand as a candidate? *contact us* if you'd like to help us with our research on how the process works and how we might be able to improve it.

…and so on.

**Comment by chris48s** [comment]
Yeah, I think this block

https://github.com/DemocracyClub/WhoCanIVoteFor/blob/master/wcivf/apps/elections/templates/elections/election_view.html#L25-L36

needs to become a bit more sophisticated based on whether the post is/is not locked

**Comment by JoeMitchell** [comment]
Few bits of feedback like this starting to come in: 

![image](https://user-images.githubusercontent.com/8096305/36665844-8aec716e-1ae0-11e8-9cce-4997bf661655.png)

**Comment by chris48s** [comment]
OK, so one case to think about is where we know about 0 candidates. Broadly I think whether the post is 'locked' or not slightly less relevant in this situation - the question is really "what do we show when we don't know about any candidates?". Although note this is what we're currently showing in this case:

https://whocanivotefor.co.uk/elections/mayor.watford.2018-05-03/post-watford/watford-borough-council

I think the other case which is more likely to be confusing (particularly at the stage where we are leading up to a scheduled election and people are starting to add candidates but SOPNs won't be out for some time) is where we know about >0 candidates but the post is not locked e.g:

https://whocanivotefor.co.uk/elections/mayor.tower-hamlets.2018-05-03/post-tower-hamlets/london-borough-of-tower-hamlets

(this is unlikely to be an uncontested election)

**Comment by JoeMitchell** [comment]
For now, wonder if a quick one-size-fits-all fix is to say

>The Adur local election will be held on **Thursday 3 May 2018**. 

>Please check back in mid-April for the final candidate list. You can [help improve our data](https://candidates.democracyclub.org.uk). 

[any candidates we do have already]

**Comment by JoeMitchell** [comment]
As @jf1 points out, it'd be awesome to link to the corresponding crowdsourcing page. 

> There's now a CTA, however...
>Here: https://whocanivotefor.co.uk/elections/local.wigan.2018-05-03/posts
>It says: Add some candidates at our candidate crowd-sourcing site
>Which links to: https://candidates.democracyclub.org.uk/
>Surely it'd be more productive to link to:
https://candidates.democracyclub.org.uk/election/local.wigan.2018-05-03/constituencies
