### ISSUE TITLE
Hackney mayor labelled as 'City Mayor'

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/WhoCanIVoteFor#236]
![image](https://user-images.githubusercontent.com/8096305/32723462-7057a634-c865-11e7-899a-531dba61eda1.png)

It's technically "Mayor of Hackney" — perhaps the catch-all is **'Directly elected mayor(s)'** ? (esp since we need to add three more)

This is on the All Elections page, which probably only gets used by superwombles, so not a massive concern. Unless its repeated somewhere else I haven't spotted yet.

**Comment by andylolz** [comment]
Yeah – ‘Directly elected mayor’ is good. (Or ‘Directly elected mayoral’ or whatever).

**Comment by symroe** [comment]
In terms of this repo, this is fixed, as it's now the job of EveryElection to give elections good names. We need to back-port the Hackney name and re-import, but there's not much to do here. 

I'll close it and open an issue on the EE repo.
