### ISSUE TITLE
mixed content warnings

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/WhoCanIVoteFor#240]
For some reason some of our links to candidate photos are over HTTP and some are HTTPS, which generates insecure/mixed content warnings. Examples:
https://whocanivotefor.co.uk/elections/local.enfield.2017-12-07/post-LBW:E05000198/enfield-highway
https://whocanivotefor.co.uk/elections/local.north-devon.2017-12-07/post-DIW:E05003554/newport

![screenshot at 2017-12-04 11 34 08](https://user-images.githubusercontent.com/6025893/33550805-296c5106-d8e7-11e7-9534-2608685ad5e7.png)

For some strange reason this is only happening on some images though. For example:

![screenshot at 2017-12-04 11 35 48](https://user-images.githubusercontent.com/6025893/33550910-85871d2c-d8e7-11e7-8798-106dbcbb6924.png)

**Comment by symroe** [comment]
I think this is fixed now
