### ISSUE TITLE
Change the background colour to grey (from white)

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/WhoCanIVoteFor#246]
The 'cards' design style looks better when the cards aren't the same colour as the background.

For example, WhereDoIVote looks better (to me) than WhoCanIVoteFor... 

![image](https://user-images.githubusercontent.com/8096305/35975534-fa70531c-0cd4-11e8-82cd-c8e0444c7ff8.png)

(Maybe a good one for 'helpwanted' or 'firsttime' — presumably quite simple?)

**Comment by chris48s** [comment]
I've moved this to https://github.com/DemocracyClub/dc_base_theme/issues/27 as it is a theme issue rather than WhoCIVF (it would also apply to the corp website)

**Comment by JoeMitchell** [comment]
Ta!
