### ISSUE TITLE
Review 'all elections', 'all parties' content

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/WhoCanIVoteFor#247]
Based on feedback from Rose:

Who are these for?
If there's a 'user journey' for them, is this the right place in the information hierarchy for them to live?

![screenshot at 2018-02-09 16 43 54](https://user-images.githubusercontent.com/6025893/36038843-b436d710-0db8-11e8-8575-b1e7352d1d90.png)

**Comment by rosewhiffen** [comment]
Blends in with the copyright/about us information?

**Comment by JoeMitchell** [comment]
I think remove the All Parties link, as does Magda. The page can continue to live for people who know where to find it :)

**Comment by pmk01** [comment]
Related: the election links on individual party pages don't actually go anywhere: https://whocanivotefor.co.uk/parties/party:790/a-vote-against-mp-expense-abuse

I think the 'all parties' page could be more useful if it had some kind of explanation on it. At present I don't know how people are supposed to interpret it. It's a list of all parties _in our database_, not all parties ever, or all active parties.

**Comment by michaeljcollinsuk** [comment]
As discussed with @pmk01 I think for now we will remove the all parties link, and rebuild the content at a later date
