### ISSUE TITLE
Confusion about historic standing

### ISSUE THREAD

**Issue by alexsdutton** [DemocracyClub/WhoCanIVoteFor#25]
https://whocanivotefor.co.uk/person/1276/kevin-mckeever claims that the candidate stood in both the Harborough and Northamptonshire South constituencies in 2015.

https://candidates.democracyclub.org.uk/person/1276/kevin-mckeever says his Harborough attempt was actually in 2010.

**Comment by andylolz** [comment]
Thanks for flagging this, @alexsdutton.

Each WhoCanIVoteFor `Post` has a unique `ynr_id` (a YourNextRepresentative Post ID), as well as an associated `election`. In YourNextRepresentative, however, `Post`s can have multiple associated elections. WhoCanIVoteFor works around this by [just picking the first associated election](https://github.com/DemocracyClub/WhoCanIVoteFor/blob/1dfc0038/wcivf/apps/elections/managers.py#L36), which I suppose was a temporary hack, and is the source of this problem.

I guess the simplest fix would be to create a new primary key on `Post`s, and remove the uniqueness constraint from `ynr_id`.

**Comment by JoeMitchell** [comment]
Perhaps related, the site is now showing two elections for https://whocanivotefor.co.uk/person/7348/susan-anne-white and a 2010 election that she didn't stand in. 

![image](https://cloud.githubusercontent.com/assets/8096305/22828461/582527b6-ef95-11e6-9946-22b9a86bc9db.png)

**Comment by symroe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix M2M bug on WCIVF](https://trello.com/c/OMx05dHs/916-fix-m2m-bug-on-wcivf)

**Comment by symroe** [comment]
I think this is fixed now – thanks all for reporting!
