### ISSUE TITLE
Explain why we don't know of any candidates before SOPNs are out

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/WhoCanIVoteFor#253]
This is an issue that applies to the way we handle a major scheduled election but can probably be ignored during the usual by-election churn if that makes things easier.

We've received a lot of negative feedback on the site over the last week or so e.g:

> No candidates listed for Chiseldon and Lawn

> Less than two months away from election and still no news on candidates. Not good enough.

> Not enough information on prospective candidates and their CV's

Today is 27th March. SOPNs will be published on 9th April. At a time like this in future, there is probably some value in making a better job of explaining to users that the reason we are showing basically no useful information in many areas is because the nominations haven't been published yet.

**Comment by andylolz** [comment]
Maybe I’m on the wrong page here – apologies if so!

> explaining to users that the reason we are showing basically no useful information in many areas is because the nominations haven't been published yet.

Shouldn’t you instead be asking users to find this information out?

For major scheduled elections, we know that we can have (semi complete) unofficial candidate lists far in advance of SOPNs being released.

**Comment by chris48s** [comment]
> Maybe I’m on the wrong page here

Nope - valid points. The CTA to go and add candidates is important - not suggesting we get rid of that. This is what we do at the moment:

![screenshot at 2018-03-27 11 21 38](https://user-images.githubusercontent.com/6025893/37961806-2d28c572-31b1-11e8-97ae-30026fa3f365.png)

Simultaneously the amount of negative feedback we're getting at the moment does suggest that this is not what people are looking for and there is also more we can do to explain. It is tricky though.

**Comment by tdg** [comment]
Could there be copy that, in order:
1) Mentions the April 9th SOPN date 
2) Suggests the voter can add candidates (now and in April)
3) Allows people to subscribe to updates for their postcode

**Comment by symroe** [comment]
Now we have https://github.com/DemocracyClub/uk-election-timetables and we show the SOPN date on the page, I think this issue is done. 

We'll have to monitor feedback to see if people still complain about lack of candidates, but at least we go some way towards telling them why now.
