### ISSUE TITLE
Revise text for template email to candidates

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/WhoCanIVoteFor#256]
Reported via slack:

> The email to ask candidates for more info still says GE 2017

e.g: https://whocanivotefor.co.uk/person/35478/email/edward-davie

/ping @JoeMitchell dunno if you have thoughts on text here given we've clearly not looked at this in a while.

**Comment by JoeMitchell** [comment]
To try to make this evergreen, I reckon ... 

> Hi,
> 
> My name is [Namey McNameFace] [[and I live in PlaceyMcPlaceFace]]. I'm volunteering for Democracy Club, which runs the UK's open election candidates database. 
> 
> Your page is here: https://candidates.democracyclub.org.uk/person/[id-mcIDface]
> 
> At the last election, Democracy Club's data was used by a number of national newspapers, search engines and civil society groups. It's a great way to reach many voters, so it's worth taking the time to make it complete.
> 
> Fortunately, I'm able to help you with this. If you or your team could send me (or, even better, send me links to public statements of) any of the missing items of information on the page given above, I would be most grateful.
> 
> You may wish to take advantage of the opportunity to provide a plain text "statement to voters" setting out your platform. If you'd like to do this, we recommend not more than 600 words.
> 
> I can update the database for you.
> 
> With best wishes,
> 
> Namey McNameFace

**Comment by chris48s** [comment]
> [[and I live in PlaceyMcPlaceFace]]

I'm guessing you're proposing just auto-populating that with the name of whatever ward/constituency/county electoral district/combined authority/[insert arbitrary unit of electoral geography here] the person being emailed is currently standing in? I reckon that's probably going to lead to a lot of sentences that a real human would never say, like:

> My name is [Namey McNameFace] and I live in Cambridgeshire and Peterborough Combined Authority

> My name is [Namey McNameFace] and I live in Blackburn South East

> My name is [Namey McNameFace] and I live in Eye, Thorney & Newborough
