### ISSUE TITLE
Election names/headings are unclear

### ISSUE THREAD

**Issue by tfgg** [DemocracyClub/WhoCanIVoteFor#26]
![image](https://cloud.githubusercontent.com/assets/103349/14556169/987c95e0-02ee-11e6-894a-b45448de891e.png)

The title

"2016 London Assembly Election (Constituencies)"

doesn't even mention my constituency (which isn't on the page anywhere!). It should say something clearer, like

"Enfield and Haringey
London Assembly Election 2016"

or similar/better :)

**Comment by JoeMitchell** [comment]
And might be nice to include the ward name at the local-election level. 
![image](https://cloud.githubusercontent.com/assets/8096305/14606809/a9bd6b10-0576-11e6-849f-51d175f30033.png)

**Comment by JoeMitchell** [comment]
This issue could be titled 'elections are unclear'.

Here's some good user feedback on London: 

> 
> You're making an assumption that people know what the elections are for, what they mean. I, and many others like me, don't. So I would suggest you pop a little '?' symbol or a 'what is this' tiny bit of text next to each of the following and explain in simple terms what the election is, and what impact it'll have:
> 
> 2016 London Assembly Election (Constituencies)
> London Mayoral Election
> 2016 London Assembly Election (Additional)
>
> Of course, I pretty much get what the middle one is, who is going to be the next Mayor of London. But I don't know what actual power they have. And how, if at all, they are linked to the other two elections. I have no idea what the London Assembly is an what it does. And no idea what the difference between Constituencies and Additional is.
> 
> So, there you have it. User research 101. I might not be the sort of person in your 'target audience', but trust me, there's a lot of people like me out there, who actually are interested and want to have a say, but have no idea really how it all ties on and what will actually make a difference. I feel some good infographics could come in use here – some nice diagrams showing visually how this all works.

Definitely a good point here, and we could borrow Wikipedia text for the tooltips (is that what they're called?).

**Comment by symroe** [comment]
I think this is fixed now?
