### ISSUE TITLE
Party logo images dead

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/WhoCanIVoteFor#296]
e.g:
https://whocanivotefor.co.uk/person/8832/rosemary-anne-beatrice-morlin
https://whocanivotefor.co.uk/person/45081/matthew-james-hull
https://whocanivotefor.co.uk/person/45080/hosnieh-djafari-marbini

![screenshot at 2018-10-11 09-26-24](https://user-images.githubusercontent.com/6025893/46790877-c2ce5e80-cd37-11e8-9100-939644fa86cc.png)

Suspect there's something that didn't get updated to account for https://github.com/DemocracyClub/yournextrepresentative/pull/633 or https://github.com/DemocracyClub/yournextrepresentative/pull/645

This might actually be an issue on the YNR side.

**Comment by hugovk** [comment]
The images are returning 403 Access Denied:

* https://candidates.democracyclub.org.uk/media/images/images/106_Emblem_106.jpg

![alt text](https://candidates.democracyclub.org.uk/media/images/images/106_Emblem_106.jpg)
