### ISSUE TITLE
Sort/group candidates in meaningful way for AMS elections with party list

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/WhoCanIVoteFor#302]
What is this trying to tell me?

![screenshot at 2018-10-30 13-45-52](https://user-images.githubusercontent.com/6025893/47722408-4817a580-dc4a-11e8-8a1b-b8694734f520.png)

This should be laid out so that candidates are obviously grouped by the party the candidate represents and ordered by number within that. The next scheduled election where we need to care about this is GLA in 2020 which uses Additional Member System.

**Comment by symroe** [comment]
I reckon this is done as part of the europarl work:

https://whocanivotefor.co.uk/elections/naw.r.mid-and-west-wales.2016-05-05/assembly-member-for-mid-and-west-wales/

Please re-open if I'm wrong.

**Comment by chris48s** [comment]
Oh yeah :+1:  this was an older dupe of the issue in #377 and #379 which I'd forgotten about
