### ISSUE TITLE
Find a way to stop getting as much spam on the feedback form

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/WhoCanIVoteFor#303]
We get a lot. It's a pain.

A CAPTCHA is too full on IMHO because:

1. It's likely to put people off
2. My guess is that there is something that would stop a lot of the dumb bots, even if not all. Stopping the dumb ones would be an improvement.

**Comment by getdave** [comment]
How about Akismet?

https://akismet.com/development/api/

**Comment by symroe** [comment]
We took the form down - so....fixed?!

We'll want to think about this if we add another form, but I'll close for now.
