### ISSUE TITLE
Fix display name for Newport West by-election

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/WhoCanIVoteFor#341]
report from user:

![newport_west_ward](https://user-images.githubusercontent.com/6025893/54223366-3cd56000-44ef-11e9-9be5-4861665dc1da.png)

---

https://github.com/DemocracyClub/WhoCanIVoteFor/blob/7de0102fc8384156ff302680d0295733f5733561/wcivf/apps/elections/models.py#L151-L164

**Comment by JoeMitchell** [comment]
Also occurring on the postcode page: e.g. [NP10 9DB](https://whocanivotefor.co.uk/elections/NP10%209DB/)
