### ISSUE TITLE
local.east-lothian.haddington-and-lammermuir.by.2019-05-09

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/WhoCanIVoteFor#351]
This election exists in EE and YNR:

* https://elections.democracyclub.org.uk/elections/local.east-lothian.haddington-and-lammermuir.by.2019-05-09/
* https://candidates.democracyclub.org.uk/elections/local.east-lothian.haddington-and-lammermuir.by.2019-05-09/

but not in WCIVF:

* https://whocanivotefor.co.uk/elections/local.east-lothian.haddington-and-lammermuir.by.2019-05-09/
* https://whocanivotefor.co.uk/api/candidates_for_ballots.json?ballot_ids=local.east-lothian.haddington-and-lammermuir.by.2019-05-09

Has one of the import jobs stopped working?

**Comment by symroe** [comment]
Just looked at this issue for the first time, and all the links are working. I assume they were meant to be broken?

So it looks like it's not *broken*, but maybe we need to import things more frequently?

I think the EE sync is daily, so postcode look ups won't show results for some time after the election is created.

**Comment by chris48s** [comment]
Meh - if it is working, I'm not too concerned. Just conscious that we're not getting any emails about failed jobs now. I found this chasing an error thrown by the dev.DC api having slightly forgotten that I'd only created this election yesterday morning. Given there is always going to be some window where an election does exist in EE but doesn't exist in WCIVF yet, maybe part of what we need to do is just handle that better..

**Comment by symroe** [comment]
Ok, I'll close this and make sure I get to #267 soon!
