### ISSUE TITLE
Header changes

### ISSUE THREAD

**Issue by magdamaciaszczyk** [DemocracyClub/WhoCanIVoteFor#357]
Changes discussed with Joe:

- Replace WCIVF logo with Democracy Club logo. The logo on mobile should take up to 50% of the screen size. From tablet screen size in portrait view, the logo should take up to 25% container width.

- A dividing line under the Democracy Club logo (1px, #DFDEDE).

- 'Who Can I Vote For?' title below (above the main page content) in Avenir regular font, same size as the `h2` element in page content.

Desktop:
![homepage-desktop-v4](https://user-images.githubusercontent.com/1705154/55165889-19a0e680-5166-11e9-828f-0863d24fab62.png)

Mobile:
![homepage-mobile-v4](https://user-images.githubusercontent.com/1705154/55165891-19a0e680-5166-11e9-888e-4fc6c89e0b89.png)

Tablet:
![homepage-tablet-v4](https://user-images.githubusercontent.com/1705154/55165892-19a0e680-5166-11e9-93bb-9411c67a84e0.png)

**Comment by symroe** [comment]
We've settled on product names in logos now and I think we should keep that for the time being. We might need to re-visit this later, but for now I'm going to close this issue.
