### ISSUE TITLE
Local elections: 'You will have {{X}} votes' not correct

### ISSUE THREAD

**Issue by BobHarper1** [DemocracyClub/WhoCanIVoteFor#370]
If I go by my postcode (postcode_view?) I get a message for the upcoming that **tells me how many votes I will have,** e.g:
> You can choose from {{9}} candidates in the {{Newry}} ward. You will have {{6}} votes.
 https://whocanivotefor.co.uk/elections/BT35%208HF/

However, if I go directly to the `election/*electionid*/*ballot*` namespace (election_view?) for the same thing I do not get this message:
> {{9}} candidates are standing in this ward.
https://whocanivotefor.co.uk/elections/local.newry-mourne-and-down.newry.2019-05-02/newry/

Now, under the first example, the statement is incorrect. There is **only one vote per person** (in my example of Northern Ireland, we use the single transferable vote preference system, but still it counts as one vote - same in Scotland).

I believe the "number of votes" is taken from the number of places that there are e.g. there are 6 seats for councillors in the example. So this isn't the same thing and it's confusing for a voter.

**Comment by chris48s** [comment]
Yes good point. This makes sense for FPTP elections but not STV because in a STV election you can rank as many or as few candidates as you like regardless of how many seats are contested. We should fix this messaging for STV elections. We should probably explain that you can vote for as many candidates as you like, but its also probably useful to indicate how many seats are up too as that might influence how many you choose to rank.

**Comment by BobHarper1** [comment]
That's a good suggestion - if it doesn't make it too trickey to implement across all the different variations.

I guess the rules are if the type is Local Election and area is in Scotland or Northern Ireland then it is an STV election. Is that straightforward to template?

In the short term and as a point of clarity for voters, can the *You will have X votes...* be removed? (it was pointed out to me by a council's staff).

**Comment by chris48s** [comment]
> I guess the rules are if the type is Local Election and area is in Scotland or Northern Ireland then it is an STV election. Is that straightforward to template?

Usefully, we explicitly store the voting system :)

https://github.com/DemocracyClub/WhoCanIVoteFor/blob/e09b2ffb9e4f774d2f5f1e7144fad22e71b71bfe/wcivf/apps/elections/models.py#L33

We'll have a look at replacing with some suitable alternative wording soon

**Comment by BobHarper1** [comment]
Suggested wording could be:

> This election uses the Single Transferable Vote system. This means you will be able to rank candidates by preference.
