### ISSUE TITLE
Breadcrumb brokenness

### ISSUE THREAD

**Issue by russss** [DemocracyClub/WhoCanIVoteFor#373]
If I go to a candidate page without searching for a postcode, and then click the "Candidates in %ward name%" breadcrumb link, it takes me to the election page rather than the ward page.

e.g. click [this link](https://whocanivotefor.co.uk/person/56927/alexander-james-scott) and then the "Candidates in Holy Trinity" breadcrumb. I'd expect it to go to [this page for the ward](https://whocanivotefor.co.uk/elections/local.guildford.holy-trinity.2019-05-02/holy-trinity/), but it actually goes to [this page for the Guildford local election](https://whocanivotefor.co.uk/elections/local.guildford.2019-05-02/guildford-local-election/).

**Comment by jf1** [comment]
Took me a mo to grasp this! Thought it worth setting it out as...

Whenever it can't be
Home | Elections in *post_code* | *candidate_name*

It should be
Home | Elections | Guildford local election | Holy Trinity | *candidate_name*

...Although I'd prefer the second option every time, ideally with names that are friendlier and more specific, such as:
Home | Elections | **2019** Guildford **Borough Council** election | Holy Trinity **ward** | *candidate_name*

This example consistently uses 'borough council' and 'ward' throughout their own documents https://www.guildford.gov.uk/electionsMay2019
Guildford Borough Council is their 'official-name' in the register https://www.registers.service.gov.uk/registers/local-authority-eng

I suspect that the 'Guildford local election' looks as strange to people there as the 'Trafford local election' looks to me. From the register ours would be the 'Trafford Metropolitan Borough Council election' or if DC were to maintain a list of friendly names for each LA then ours would be the 'Trafford Council election' to align with their friendly name as used at eg https://www.trafford.gov.uk

**Comment by russss** [comment]
To be clear - the issue I was reporting was purely that the link goes to the wrong place. The link says "Candidates in Holy Trinity [ward]" but it goes to the "Guildford local election" page. However, those changes definitely sound worthwhile too!

**Comment by jf1** [comment]
Absolutely, I worked that out (eventually!) and thought that as well as fixing the mismatched label/link combo, the full breadcrumb trail could be used at least in those scenarios but I think it's worth considering full/consistent breadcrumbs at all times - users could navigate back or reenter their postcode if necessary.
