### ISSUE TITLE
'How you vote' doesn't actually say how you vote

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/WhoCanIVoteFor#375]
I'd totally forgotten this was a thing: 

![image](https://user-images.githubusercontent.com/8096305/56351792-c995cc80-61c5-11e9-946f-1b9c53798365.png)

Having clicked the little arrow, I was expecting it to say "You mark an X in the box for your choice". But instead it confused me about acronyms.

Might be nice to embed a video here, depending on the type of election, e.g. [how to vote in local elections in England](https://www.youtube.com/watch?v=KGTeHJ7i0xg) — although it'll just make us look more like the EC :D

**Comment by symroe** [comment]
This is the same as https://trello.com/c/8L4XRexe. 

The text comes from EE. I expect the work is to write something against each voting system (or at least the ones we have active at the moment)

**Comment by JoeMitchell** [comment]
For European ballots, we put the how to vote _above_ the people, rather than in a How you vote dropdown

![image](https://user-images.githubusercontent.com/8096305/56739399-70e6a680-6766-11e9-812a-a8babf28ad42.png)

I think we should chop that sentence, and add some text to the relevant bit of EE. 

My suggestions for the EE texts:

FPTP: 
>Mark an X in the box for your preferred candidate(s). For more information, visit The Electoral Commission's website or ask an official at your polling station.

STV: 
>Rank the candidates by your preference: 1, 2, 3... You don't have to rank all the candidates, but you must at least mark your first choice. For more information, visit The Electoral Commission's website or ask an official at your polling station.

WhateverthehelltheEurosis: 
>Mark an X in the box for one party or independent candidate. For more information, visit The Electoral Commission's website or ask an official at your polling station.

MVP version of 'How to vote', for every election, a la the Electoral Commission:

>Read the instructions at the top of your ballot paper carefully. If in doubt, ask an official at the polling station. 

Small steps in the right direction, at least...

**Comment by JoeMitchell** [comment]
Although now I'm worried that people will think they somehow vote via our website :D

**Comment by JoeMitchell** [comment]
Okay absolute last comment on this, but in case for future reference we want to explain the systems, rather than say what-you-do-as-a-voter, [parliament's site](https://www.parliament.uk/about/how/elections-and-voting/voting-systems/) is good here.

**Comment by symroe** [comment]
Thanks for this!

To be clear: is this a suggestion to keep the interface as is (apart from cutting the text above the candidate list for the europarl), and just change the text in the expandable section?

If so, then I think this is an EE issue, and it'll sync over once changed there…

**Comment by JoeMitchell** [comment]
Yes, that's right. 👍

**Comment by chris48s** [comment]
Those bits of text (descriptions of voting systems) live in the WCIVF DB. They were inserted in this migration: https://github.com/DemocracyClub/WhoCanIVoteFor/blob/master/wcivf/apps/elections/migrations/0025_auto_20190412_1528.py (that's possibly not ideal). They don't come from the EE API

**Comment by chris48s** [comment]
tbh, this text is probably better off moving to a template where its easy to edit anyway

**Comment by symroe** [comment]
Done – this will populate for the EUs after an import over night
