### ISSUE TITLE
Strange behaviour for rescheduled ballot

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/WhoCanIVoteFor#378]
https://whocanivotefor.co.uk/elections/local.tendring.st-osyth.by.2019-05-23/ currently shows no candidates (which is right at the time of raising this because we haven't entered any in YNR yet)

For some reason, https://whocanivotefor.co.uk/api/candidates_for_ballots/?ballot_ids=local.tendring.st-osyth.by.2019-05-23 and https://whocanivotefor.co.uk/elections/CO16%208EZ/ are showing the candidate list for `local.tendring.st-osyth.2019-05-02` which `local.tendring.st-osyth.by.2019-05-23` replaces.

This is misleading because although the nominations for `local.tendring.st-osyth.2019-05-02` carry forward for `local.tendring.st-osyth.by.2019-05-23`, one of the candidates won't be on the list because the reason the elections was rescheduled is because one of the candidates died.

**Comment by chris48s** [comment]
Right. I've had a quick dig about in this. I'm not 100% but I'm _fairly_ sure that the problem is that we're caching candidate lists based on the `Post` instead of the `PostElection` (or ballot id) and in this case, the YNR post ID for both elections is `DIW:st-osyth`.

This may also be causing other problem in the vein of https://github.com/DemocracyClub/yournextrepresentative/issues/929

It might be that this is as simple as changing https://github.com/DemocracyClub/WhoCanIVoteFor/blob/da911d4ffbd118c05a42f5c71c28fe57035e0654/wcivf/apps/elections/views/mixins.py#L86-L106 to key off the ballot instead of the post and clearing the cache to deploy, but it might be that there are other wider implications of this. I don't have quite enough of a high-level overview of this codebase to understand what else makes or depends on this assumption..

**Comment by symroe** [comment]
As per #382 the cache is now:

* Keyed on the ballot
* Cleared on each full import

This should have sorted this one out, marking as closed unless we find otherwise
