### ISSUE TITLE
Odd stuff happening with list candidates in London

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/WhoCanIVoteFor#39]
![elections_in_se18_2uj___whocanivotefor_](https://cloud.githubusercontent.com/assets/8096305/14941337/27183686-0f8f-11e6-8747-a7d520d9184d.png)

Parties are being split ... should be only occuring once...

**Comment by JoeMitchell** [comment]
Looks like this is only a problem in London, and only with BNP and Britain First.

(Tested Cardiff and Edinburgh postcodes - they seem fine)

**Comment by andylolz** [comment]
Testing with the URL in the screenshot above, this appears to be fixed.
