### ISSUE TITLE
Make it clearer if a candidate is one of many standing for a party

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/WhoCanIVoteFor#404]
It is slightly odd phrasing to frame someone as "**the** party X candidate" when that party is fielding lots of candidates:

![Screenshot at 2019-05-18 22-58-16](https://user-images.githubusercontent.com/6025893/57975412-6f547b00-79c0-11e9-8672-588229589bc0.png)

This applies to party list elections, but also in local elections where a party will field multiple candidates in a multi-seat ward.

**Comment by symroe** [comment]
I reckon this is done? @VirginiaDooley?
