### ISSUE TITLE
Change opening times on the polling stations card for City of London Alderman/Councilman elections

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/WhoCanIVoteFor#441]
https://github.com/DemocracyClub/WhoCanIVoteFor/commit/c4edbe9bb2d6237044090aeb55a84191cab1d171 bodges the poll close date in the ballot detail card, but if **all** of the relevant elections matched by a postcode search are City of London local elections, that info should be passed to the polling stations card so we can modify the opening times there too. At the moment we say 8pm on the election detail card but then 10pm on the polling stations card.

Edge case: I'm not entirely sure what happens if there is say a CoL Alderman by-election on the same day as a parliamentary election or something..

This may become irrelevant if we get to https://github.com/DemocracyClub/EveryElection/issues/581 first.

**Comment by symroe** [comment]
@michaeljcollinsuk I think you might have fixed this? Please close if so!

**Comment by chris48s** [comment]
If you've done the research to resolve the edge case, satisfy my curiosity: If there's a CoL local election and another election on the same day, what happens? Do they extend the hours for the local election, or do you get 2 ballot papers if you walk into the polling station at 7:59pm but only 1 paper if you walk in at 8:01pm?

**Comment by symroe** [comment]
I don't think we've resolved that yet! But, I don't think The City Of
London has either... We found a document that explained it would be....
Tricky to have them on the same day, so they moved them rather than deal
with it. I'm quite happy with this solution!

**Comment by chris48s** [comment]
![0or2tbpf4fs11](https://user-images.githubusercontent.com/6025893/106521689-83af1300-64d6-11eb-8ddb-a3b641129b99.jpg)

**Comment by michaeljcollinsuk** [comment]
> @michaeljcollinsuk I think you might have fixed this? Please close if so!

Yes this was resolved in #623 https://github.com/DemocracyClub/WhoCanIVoteFor/pull/623/commits/eeaa1cb3bb507ca74a6ad20225bb5d85d38ec3ed so I will close this

**Comment by chris48s** [comment]
It looks like it is still hard-coded to me:
https://github.com/DemocracyClub/WhoCanIVoteFor/blob/77b3195bf39b5b64530c74faadb807ee4f381349/wcivf/apps/elections/templates/elections/includes/_polling_place.html#L49

**Comment by michaeljcollinsuk** [comment]
> It looks like it is still hard-coded to me:
> 
> https://github.com/DemocracyClub/WhoCanIVoteFor/blob/77b3195bf39b5b64530c74faadb807ee4f381349/wcivf/apps/elections/templates/elections/includes/_polling_place.html#L49

Ah sorry, I missed this include! I'll resolve - are you able to reopen the issue (don't think I can reopen one that I didnt create)
