### ISSUE TITLE
Handle deleted elections

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/WhoCanIVoteFor#456]
`import_elections` / `import_posts` should handle the case where an election is created in error and then soft-deleted in EE

**Comment by michaeljcollinsuk** [comment]
@symroe I've had a little look in to this, and from what I can see there is a [`deleted` field](https://github.com/DemocracyClub/EveryElection/blob/master/every_election/apps/api/serializers.py#L184) that is exposed on the EveryElection API to indicate that an election was 'soft-deleted'. But this is not currently being used in the [`get_or_create_election`](https://github.com/DemocracyClub/yournextrepresentative/blob/master/ynr/apps/elections/uk/every_election.py#L69) method used by the Every Election importer in YNR.

So I think to resolve this issue the initial changes need to occur in YNR to account for the deleted value when elections are imported from EveryElection. I see a couple of options here:
1) store the 'deleted' value against the model and then expose this field over the candidates API
2) do not import elections/posts that are marked as 'deleted' within YNR.
