### ISSUE TITLE
Facebook profile should be linked to if no campaign page specified

### ISSUE THREAD

**Issue by gwire** [DemocracyClub/WhoCanIVoteFor#54]
Currently it appears that the link for Facebook only applies to a page and not a profile.

e.g. [10294](https://candidates.democracyclub.org.uk/person/10294/) contains a Facebook personal URL but this is not linked to on the [WCIVF candidate page](https://whocanivotefor.co.uk/person/10294/richard-james-adair).

```
    "facebook_page_url": "", 
    "facebook_personal_url": "https://www.facebook.com/richard_adair-898694793535041/", 
```

**Comment by annapowellsmith** [comment]
Closed with #186
