### ISSUE TITLE
Problems opening external links? 

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/WhoCanIVoteFor#57]
Feedback from F: 

> One thing that niggles however is that the links don’t open when I click them, I have to right click and say open in a new tab. Is that just me or a specific functionality?
> 
> Oh dear! I’m using Safari 9.0.3 and it’s just the links to the candidates’ external sites. Links internally seem to work fine.

**Comment by andylolz** [comment]
Looks to have been fixed in: 9c4c23f.
