### ISSUE TITLE
The 0 candidates

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/WhoCanIVoteFor#596]
![Zero](https://user-images.githubusercontent.com/61510609/99378165-06a0d400-28bf-11eb-8522-aed27d7c88bf.png)

The preview text on WCIVF tabs reads '0 candidates' regardless of the number of candidates on page.

**Comment by symroe** [comment]
* [ ] Use @michaeljcollinsuk's new `current_or_future` queryset in the template - but consider what happens when we don't have any curent candidacies
* [ ] write a test for this
