### ISSUE TITLE
Remove email reminder card

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/WhoCanIVoteFor#597]
We don't really make use of this, best remove it until we can actually offer the service!

**Comment by VirginiaDooley** [comment]
> We don't really make use of this, best remove it until we can actually offer the service!
@pmk01 Does this issue refer to the election reminder/subscription card?

**Comment by pmk01** [comment]
Hello, yes! There's a Trello card too: https://trello.com/c/pExbg7nU

Sadly it's not a service we're set up to deliver at present (and there aren't any elections to remind people about anyway!) so we should remove the sign up form for now.

**Comment by chris48s** [comment]
If you're giving up on this, note it also exits in WDIV https://github.com/DemocracyClub/UK-Polling-Stations/blob/3c5150200afd906092f60385d7690260d9e823dd/polling_stations/templates/postcode_view.html#L89-L93 but is also kinda tied into generating mailing list signups via  https://github.com/DemocracyClub/dc_signup_form
Dunno if you're giving up on that too

**Comment by symroe** [comment]
Thanks Chris! Yeah, the trello card includes WDIV, but also notifying and deleting the list of people signed up - this PR is just a small part of that :+1:
