### ISSUE TITLE
Stop saying 'area'

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/WhoCanIVoteFor#608]
I think this should read:

🗳️ Senedd Cymru elections 🗳️
Blaenau Gwent constituency

(apply change to Scottish parl., London Assembly, etc, etc.

![Screenshot 2020-12-22 155831](https://user-images.githubusercontent.com/61510609/102907873-8dbd0b00-446e-11eb-95cc-a52872c47436.png)

**Comment by pmk01** [comment]
**UK Parliament:** Constituency 

**Scottish parliament (constituencies), Senedd (constituencies), London Assembly (Constituencies):** 
For these I think we should remove the bracketed "(constituencies)" and instead display:

🗳️ Senedd Cymru elections 🗳️
Blaenau Gwent constituency

**Senedd and Scottish (additional)**
Again, we should remove the bracketed word and display these as:

🗳️ Senedd Cymru elections 🗳️
Mid and West Wales region

**London Assembly elections (Additional)**

This is a bit more awkward, as there's only the one region. Perhaps:

🗳️ London Assembly elections🗳️
Additional members
(be good to have @symroe and @GeoWill 's views on this one!)

For councils, you're not going to like this but there are differences which I forgot when we spoke - some are _Wards_ and others are _Divisions_. @GeoWill recently went through County Council divisions so might be able to give a full answer, but I'll look now and post again with my thoughts on that...

**Comment by pmk01** [comment]
Well now, what an adventure this is turning out to be.

In Scotland, a councillor is elected to a _Ward_.

In Wales, a councillor is elected to a _Ward_.

In Northern Ireland, a councillor is elected to an _electoral area_. (in fact, it might be easier to simply retain 'area' for these elections, as 'electoral area' might be a bit meaningless for most people).

In England it's _complicated_, and I will try to get to the bottom of it in the third exciting instalment of this saga.

**Comment by pmk01** [comment]
Well now, what an adventure this is turning out to be.

In Scotland, a councillor is elected to a _Ward_.

In Wales, a councillor is elected to a _Ward_.

In Northern Ireland, a councillor is elected to an _electoral area_. (in fact, it might be easier to simply retain 'area' for these elections, as 'electoral area' might be a bit meaningless for most people).

In England it's _complicated_, and I will try to get to the bottom of it in the third exciting instalment of this saga.

**Comment by pmk01** [comment]
Q. When is a ward not not a ward?
A. When it's in post-2009 unitary county council.

Right, so, I think I have worked this out. For more info (as I am sure you are all _fascinated_), [here's a handy overview of wards and divisions in England.](https://www.ons.gov.uk/methodology/geography/ukgeographies/administrativegeography/england#electoral-wards-electoral-divisions)

- In English District councils, a councillor is elected to a _Ward_.

- In English County Councils, a councillor is elected to a _Division_.

In case you suspect that this difference is entirely academic, a practical reason for changing our County Council pages to 'Division' is that some District Wards and County Divisions have the same name and cover a similar area, see [Cambridge](https://whocanivotefor.co.uk/elections/local.cambridge.abbey.2021-05-06/abbey/) and [Cambridgeshire](https://whocanivotefor.co.uk/elections/local.cambridgeshire.abbey.2021-05-06/abbey/). Renaming the latter to _Division_ could help avoid confusion.

- In English Unitary Authorities, a councillor is elected to a _Ward_.

But it wouldn't be England if there were no exceptions! It seems that Unitary Authorities created out of County Councils (eg. Shropshire, Wiltshire, Isle of Wight) retain the term _Division_, for what are now _Wards_. Should we reflect this on our site? Does it matter? Regardless, I think the answer to which UAs are Counties is held in this (quite large) [LGBCE spreadsheet.](https://www.lgbce.org.uk/resources/electoral-data)

- Finally, on the Isles of Scilly, a councillor is elected to a [_Parish_.](https://www.scilly.gov.uk/news/council-election-results-4-may-2017) Presumably this is because neither Ward nor Division were regarded as quaint enough.

**Comment by chris48s** [comment]
In terms of implementation, this information broadly exists in EE.
If you look at the API response for say

https://elections.democracyclub.org.uk/api/elections/local.worcestershire.alvechurch.2021-05-06/
the division object has

```
"division_type": "CED",
"division_subtype": "County council electoral division",
```

whereas https://elections.democracyclub.org.uk/api/elections/local.adur.buckingham.2021-05-06/ will tell you

```
"division_type": "DIW",
"division_subtype": "District council ward",
```

and https://elections.democracyclub.org.uk/api/elections/senedd.c.aberavon.2021-05-06/ will tell you

```
"division_type": "WAC",
"division_subtype": "Welsh Assembly constituency",
```

You might want to map those to "friendly" names e.g: "District council ward" --> "ward", but really this should be about consuming  and surfacing data that already exists in EE. You don't need to re-invent the wheel here.

EE also already knows about  the obscurities of unitary county divisions e.g:

https://elections.democracyclub.org.uk/api/elections/local.northumberland.alnwick.2021-05-06/

```
"division_type": "UTE",
"division_subtype": "Unitary Authority electoral division (UTE)",
```

It **should** know about Isles of Scilly Parishes too (COP), but for some reason those seem to be coded as DIW (district ward) which is wrong.. so maybe there's a bit of clean-up needed there :thinking:

**Comment by pmk01** [comment]
![Screenshot 2021-01-20 091537](https://user-images.githubusercontent.com/61510609/105153250-1f687880-5b00-11eb-902c-e38fa6806184.png)

I forgot about NI Assembly... this should read _constituency_ (and we can get rid of "Member of the Legislative Assembly for").

**Comment by chris48s** [comment]
I was thinking about this issue some more last night and remembered that

a) The `division_subtype` field has a stupid name for the content it has - it should really be like `division_description` or something
b) I might have given up bothering to populate it at some point
c) We actually strip this field in the https://developers.democracyclub.org.uk/ API for these reasons https://github.com/DemocracyClub/aggregator-api/pull/62#discussion_r300618080

That said, Isles of Scilly aside you probably **can** rely on `division_type` being populated and accurate. I suspect @GeoWill  is bang on the case with this already, but the codes are:

* CED: County Electoral Division
* COP: Isles of Scilly Parish
* DIW: District Ward
* EUR: European Parliament Region (for historic purposes)
* LAC: London Assembly Constituency
* LBW: London Borough Ward
* LGE: NI Electoral Area
* MTW: Metropolitan District Ward
* NIE: NI Assembly Constituency
* SPC: Scottish Parliament Constituency
* SPE: Scottish Parliament Region
* UTE: Unitary Authority Electoral Division
* UTW: Unitary Authority Ward
* WAC: Welsh Assembly Constituency
* WAE: Welsh Assembly Region
* WMC: Westminster Parliamentary Constituency

**Comment by chris48s** [comment]
..of course (as always) _its a bit more complicated than that_. The other two cases are Mayors and PCCs, who don't represent a division. You can look at the `organisation_type` key in the EE API to work out the right word.

The governance system for police forces is complicated. The right word might be force, or authority.. or area. That's probably a research point for Peter, but it should be the same word for all of them.

Mayors are slightly more of a mixed bag. Some of them represent a council and some represent a combined authority, but again: `organisation_type`.

**Comment by pmk01** [comment]
Thanks Chris! [The Cabinet Office-maintained website](https://www.choosemypcc.org.uk/) uses 'Police force area', so I think we should copy them.
