### ISSUE TITLE
Mayor of the West Yorkshire Combined Authority

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/WhoCanIVoteFor#614]
Remove the 'the'

https://whocanivotefor.co.uk/elections/mayor.west-yorkshire.2021-05-06/mayor-of-the-west-yorkshire-combined-authority/

**Comment by michaeljcollinsuk** [comment]
@symroe I think this requires a change in the Every Election database so that this is then imported by YNR and then WCIVF. Also following discussion with @pmk01 I think all mayoral elections need "election" added to their name. Can you recommend the best way for me to go about making these changes?

**Comment by michaeljcollinsuk** [comment]
This is also related on how we display the description on candidates pages outlined in this document https://docs.google.com/document/d/1yQdJRj-eh9UL5B7MJ87Wmr7WRBfFV29IVfWi7VQHhfc/edit#

**Comment by michaeljcollinsuk** [comment]
I've removed the 'the' in the Every Election. Will check if that gets populated in WCIVF at the next import from YNR

**Comment by symroe** [comment]
Looks like that worked! :tada:

**Comment by symroe** [comment]
We still have "the West Yorkshire Combined Authority area" in the paragraph, but that's a different issue
