### ISSUE TITLE
Update code to run without Redis locally

### ISSUE THREAD

**Issue by michaeljcollinsuk** [DemocracyClub/WhoCanIVoteFor#620]
It seems there are some assumptions in the code that Redis is running. So for example when attempting to run the project with dummy cache, when submitting a postcode a Redis connection error occurs. Similarly, there a few tests that rely on having Redis running. This could be refactored to allow using the dummy cache

**Comment by symroe** [comment]
Good catch - I don't think we're using Redis in any special ways that mean we can't just wrap it in Django's cache framework

**Comment by michaeljcollinsuk** [comment]
Having looked in to this a bit closer its not actually using Redis for caching that's causing this, it appears to be when we try to add a searched postcode to a task queue to create a LoggedPostcode object https://github.com/DemocracyClub/WhoCanIVoteFor/blob/master/wcivf/apps/core/models.py#L21

So I think we could add a settings variable that could be enabled in a local settings file that bypasses using Redis? Or doesn't log postcodes at all.
