### ISSUE TITLE
New person page designs

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/WhoCanIVoteFor#640]
This is a "parent" issue for grouping other work in redesigning the person pages.

* [Miro board](https://miro.com/app/board/o9J_lXc5_oM=/)
* [Google doc](https://docs.google.com/document/d/117TOzt6aoLlZymgCTxIZ-Pg1639sx4KUjiLukpsGHwc/edit#heading=h.p21udmlttcl3)
* Related issues
    *  #211
    * #599
    * #202 
    * #198 
    * #404 
  
# Progress
* [x] Remove all inline CTAs
* [x] Redesign "previous elections" card
* [x] Redesign "contact" card
* [x] Make intro paragraph better in all cases

## Remove all inline CTAs
We ask users to add or edit data in various places at the moment. This clutters the pages, and no one ever clicks on them.

It would be better to make it clear in one place that this data can be edited - let's add a card at the bottom of ever person page that explains this, but remove all other CTAs

## Redesign "previous elections" card

Convert to a table, but consider long party and person names on mobile - can we make a responsive table class somehow?

Initial design:

![Screenshot from 2021-01-27 19-00-40](https://user-images.githubusercontent.com/242329/106040170-f9c80a00-60d1-11eb-9c39-38c340c42ded.png)

## Redesign "contact" card

1. Put links next to each other
2. Remove extra data in the link text - e.g we don't need "https://", we don't need "facebook.com/" or "twitter.com/" etc
3. Merge "latest Tweets" with this card
4. Call it something like "[person name] online", rather than "contact info"

![Screenshot from 2021-01-27 19-04-05](https://user-images.githubusercontent.com/242329/106040489-735ff800-60d2-11eb-8e31-b7ec214be515.png)

## Make intro paragraph better in all cases

There is some value in having a paragraph at the top of the page, but the one we have is too simplistic. I think we should generate this paragraph in a much better way, taking in to account all the cases we know about.

One issue here (and elsewhere, like "previous elections" is that we don't know all the elections someone has stood in, only the ones that we have covered. We need to explain this somehow.

**Comment by VirginiaDooley** [comment]
@symroe There is [some code related associated companies that is currently commented out](https://github.com/DemocracyClub/WhoCanIVoteFor/blob/b1f4cdb369986d27b554f6f92e5fe7b4d1c5fefe/wcivf/apps/people/templates/people/person_detail.html#L187). Should any of this be carried over to the new person page template?
