### ISSUE TITLE
Links on postcode results page do nothing

### ISSUE THREAD

**Issue by michaeljcollinsuk** [DemocracyClub/WhoCanIVoteFor#653]
The results page after searching for a postcode has links that do nothing. Should these be anchor links to take user to correct section of the page? Or link to the postview page?

Example url: https://whocanivotefor.co.uk/elections/S11%207GG/

**Comment by VirginiaDooley** [comment]
It looks like this has been addressed - unless the answer was link to postview page?

**Comment by symroe** [comment]
I agree it looks done — @michaeljcollinsuk can you confirm please?

**Comment by michaeljcollinsuk** [comment]
Yes this was resolved in previous PR
