### ISSUE TITLE
'show candidates' link doesn't expand candidates panel for party list elections in some browsers

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/WhoCanIVoteFor#676]
### Issue and Steps to Reproduce

This might be a base theme issue rather than WCIVF itself, but the 'show candidates' link for party list elections works in Firefox, but doesn't expand the candidates panel in at least one other browser (the only one I've tested is Chromium). See screen-grabs..

#### Firefox (works fine):

![GIFrecord_2021-02-24_175732](https://user-images.githubusercontent.com/6025893/109045111-19e7ea80-76cb-11eb-9b1d-225ca31c3475.gif)

#### Chrome (does nothing):

![GIFrecord_2021-02-24_175823](https://user-images.githubusercontent.com/6025893/109045148-266c4300-76cb-11eb-9151-ca6983e4e2c2.gif)

Hopefully someone else can reproduce this and I'm not completely mental.

**Comment by sjorford** [comment]
I get the same in Chrome if I click on "Show candidates", but clicking anywhere to the right works:

![image](https://user-images.githubusercontent.com/10633357/109414797-ba305e80-79ac-11eb-88ab-d4dc4bee60c1.png)

I think it's the `<a>` wrapping "Show candidates" that is causing Chrome to ignore the behaviour of the `<details>` element:

https://github.com/DemocracyClub/WhoCanIVoteFor/blob/d1b8aa675e6cbbf2c9108c8f09cc02423e9327ed/wcivf/apps/elections/templates/elections/includes/_people_list_with_lists.html#L58-L67
