### ISSUE TITLE
Candidate names become invisible at narrow enough window widths

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/WhoCanIVoteFor#677]
### Issue and Steps to Reproduce

Candidates with sufficiently long names (but not that long, really - e.g: "Samantha") are shown as having no name at all or partial name if the window width is sufficiently narrow. e.g: "Samantha Chohan" and "Atlaf Hussain" in below example:

### Screenshots

![GIFrecord_2021-02-24_180245](https://user-images.githubusercontent.com/6025893/109045587-aeeae380-76cb-11eb-900a-1a0dcd715ce1.gif)

This probably happens at a much wider point for candidates with actually long names, but I couldn't be bothered to find an example ;) Suspect the solution here is either to make the cards have variable height or collapse to mobile/vertical layout at a higher width.

**Comment by VirginiaDooley** [comment]
Design system handles responsiveness so this is no longer an issue.
