### ISSUE TITLE
Regional ballot text.

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/WhoCanIVoteFor#726]
Affects: sp.r, senedd.r, gla.a

eg. https://whocanivotefor.co.uk/elections/sp.r.lothian.2021-05-06/lothian/

We're currently telling people they 'can choose from n candidates'

This is wrong, they pick parties or independent candidates. Ideally the text should read 'n ballot options'.

So the text from the Lothian list should be: 

"You can choose from 19 ballot options in the Lothian region."

**Comment by VirginiaDooley** [comment]
Should this also be the case when the 'candidate list has not been published'? @pmk01
