### ISSUE TITLE
Resetting Results- 'Unset winners button'

### ISSUE THREAD

**Issue by KateSeary** [DemocracyClub/WhoCanIVoteFor#741]
### Additional Details
* Browser and version
* Were you logged in?

**Comment by VirginiaDooley** [comment]
@KateSeary I think this was meant for YNR (and I think it was implemented there per image below) so will close this. 
![Screen Shot 2021-05-10 at 1 18 15 PM](https://user-images.githubusercontent.com/7017118/117658068-38219a80-b192-11eb-9452-558beb3879e8.png)
