### ISSUE TITLE
Parish card not always given anchor link in top card

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/WhoCanIVoteFor#750]
Compare

https://whocanivotefor.co.uk/elections/GL5%204HA/

with 

https://whocanivotefor.co.uk/elections/GL5%201NA/

The first has a link to the parish council election and the card lower down the page. The second has the card, but no link.

**Comment by pmk01** [comment]
Yes, to be honest I am fine with it as it is, but if you've already worked out the fix I agree entirely with your last suggestion!
