### ISSUE TITLE
Change 'Elections' box on candidate pages

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/WhoCanIVoteFor#76]
WCIVF displays candidacy information a bit awkwardly. 

![image](https://cloud.githubusercontent.com/assets/8096305/23661677/4e18f568-0345-11e7-907b-6c0b7fe0c65b.png)

I think we should just have a heading of Candidacies, then bullet points, e.g.:  

### Candidacies
- 2017 Copeland parliamentary by-election (UKIP)
- 2016 Morton ward, Carlisle local election (UKIP)

Ideally [Copeland] and [Morton ward] would be hyperlinked too. 

(This might link with [#67 on YNR issues](https://github.com/DemocracyClub/yournextrepresentative/issues/67))

**Comment by annapowellsmith** [comment]
We no longer display this card. Joe is making a new issue to add historical candidacies.
