### ISSUE TITLE
"You can choose from N ballot options" number is wrong?

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/WhoCanIVoteFor#761]
I'm not really sure what this number is trying to tell me. I guess it is either supposed to be either:

- The total number of things (people or parties) that will be on the ballot paper or
- The number of those things (people or parties) that I can vote for in some way

but the number doesn't correspond to either of those things. For example:

This is a Supplementary Vote ballot with 6 people standing. I can vote for 2 of them (first and second preference):

![Screenshot at 2021-04-21 17-25-05](https://user-images.githubusercontent.com/6025893/115588738-f5714e80-a2c6-11eb-9c1b-06e35ac0a28a.png)

---

This is a PR ballot with 14 total things standing (13 parties plus one independent candidate). I can vote for one of them:

![Screenshot at 2021-04-21 17-25-25](https://user-images.githubusercontent.com/6025893/115588779-01f5a700-a2c7-11eb-816e-51f7dcc007ea.png)

Not sure if the feature is broken or working and I don't understand what it is trying to tell me. If its the second one, I suspect it is unclear to others too and this could be phrased more clearly.

**Comment by symroe** [comment]
I think we might have fixed this already, but not deployed it yet. Can you check on https://test.whocanivotefor.co.uk and confirm if it's improved?

**Comment by chris48s** [comment]
Yes - that does appear to be fixed now and more clearly phrased :+1: 

This definitely shouldn't be a blocker to deploying that because it is a big improvement but...

The one further minor suggestion I would have is: On party list elections the caption is something like "You will have one vote, and can choose from 10 **candidates** ", whereas actually you've got way more candidates standing than that. That's the number of [parties or people]. Obviously this is difficult because parties can field a list and independents can also stand too so you've got 10.. things there isn't a single nice word for, but it would probably be clearer to say "You will have one vote, and can choose from 10 parties" (accepting that in some case that means 10 parties and in some cases it means 8 parties and 2 independents, or whatever). I think that would be a better explanation and a fairly simple change to make.

The really nice solution would be to actually present that as  "You will have one vote, and can choose from 8 parties and 2 independent candidates" or whatever where that is the case (which you do have the data for), but y'know.. priorities :)

**Comment by sjorford** [comment]
This may be a stupid question, but what wording does the ballot paper use?

**Comment by chris48s** [comment]
Definitely not a stupid question - I had not thought to look until you mentioned it, although having done so I don't think it provides a neat answer :laughing: 

In Wales the ballot for the party list election will look like this:
![Screenshot at 2021-04-21 21-07-43](https://user-images.githubusercontent.com/6025893/115614694-e5b53280-a2e5-11eb-9790-2f25e9ab236a.png)

which neatly sidesteps the issue of finding a single noun to describes "party list or independent candidate" by just saying "box". I don't have an example handy for Scotland or London but i suspect they do the same.

**Comment by sjorford** [comment]
things would be so much easier if we just voted for boxes

![image](https://user-images.githubusercontent.com/10633357/115615608-177ac900-a2e7-11eb-944f-3865791705d3.png)
