### ISSUE TITLE
City of London: no wards? 

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/WhoCanIVoteFor#77]
Do we have the ward-level geographies for the City of London? (They're probably not called wards in the City, but battels or fiefdoms or something... but you know what I mean. 

At the moment, it's just dumping me in the overall election...

![image](https://cloud.githubusercontent.com/assets/8096305/23668739/e01a68b6-0359-11e7-946d-a734314cb1c8.png)

**Comment by symroe** [comment]
This was my fault! Typo! Fixed in a27f76fd5e1773ab6da7f0416dcd4fe85024ad48
