### ISSUE TITLE
Reorder information on candidate pages

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/WhoCanIVoteFor#78]
A wise man once said:

>so, in terms of “Learning more about this candidate”, I think an email address is the least useful thing. A wikipedia link, a website address, a twitter account are all more useful. 

Agreed. One would then email one's candidate if the information above wasn't enough.

**Comment by symroe** [comment]
Either done or taken care of in other issues, I think?

**Comment by annapowellsmith** [comment]
Email address ordering fixed in https://github.com/DemocracyClub/WhoCanIVoteFor/commit/8312ae7149d66867776bfca7c133a4e0a490fe08 and the card with the email in is always last.
