### ISSUE TITLE
Put the biscuits back

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/WhoCanIVoteFor#789]
We're not displaying biscuit preferences on WCIVF

**Comment by VirginiaDooley** [comment]
Fixed in https://github.com/DemocracyClub/WhoCanIVoteFor/pull/792 
![Screen Shot 2021-05-10 at 9 45 26 AM](https://user-images.githubusercontent.com/7017118/117631776-790ab680-b174-11eb-899f-0a5e158dc9b6.png)
