### ISSUE TITLE
Improve OG image

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/WhoCanIVoteFor#79]
Not sure what image it should use.

**Comment by annapowellsmith** [comment]
on candidate page we use candidate images: is this for other pages?

**Comment by annapowellsmith** [comment]
I think we should use candidate images for candidate pages, party logos for party pages, and the DC logo everywhere else. Should check that candidate images are working, I think they may be broken.

**Comment by annapowellsmith** [comment]
Fixed with #176
