### ISSUE TITLE
Small error in the Additional Member System page (ams.html)

### ISSUE THREAD

**Issue by arcturis** [DemocracyClub/WhoCanIVoteFor#794]
### Issue and Steps to Reproduce
Hi, I believe you have a small error on your Additional Member System page:
```https://whocanivotefor.co.uk/elections/voting_system/ams/```

In the example election table you list Lib. Dems as winning 12,097 seats which is really quite the landslide victory in a 10-seat election! I think the data in the row has got shifted to the left by one and an additional "No Change" td element has been added.

Looks like it's being sourced from here:
https://github.com/DemocracyClub/WhoCanIVoteFor/blob/f9dbebef36a42fcf6ee63e1abf886542a02173ba/wcivf/apps/elections/templates/elections/ams.html#L142

### Screenshot
![wcivf_ams_table_problem](https://user-images.githubusercontent.com/26504908/117179299-17baae80-ae27-11eb-8815-63cbcd134a8c.png)

Great work on the site by the way! Its been an invaluable source of information about the upcoming elections.

**Comment by VirginiaDooley** [comment]
@pmk01 can you verify and I'll make the edit?
