### ISSUE TITLE
A way to get back to full list of candidates from a single candidate page

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/WhoCanIVoteFor#80]

**Comment by davidmiller** [comment]
Back to full candidates for a particular election ?

**Comment by JoeMitchell** [comment]
Ooh, I think this is fixed now, with the postcode breadcrumb trail?

**Comment by symroe** [comment]
Might be too subtle?

**Comment by JoeMitchell** [comment]
Needs user-testing!

**Comment by annapowellsmith** [comment]
Might also add a "Back to all candidates in <constituency>" button, underneath the "Homepage, contact etc" button. 

If they're engaged they'll carry on reading down the page. But I feel a back link is probably more useful for the majority of casual readers than plunging them into appeals for crowdsourcing.
