### ISSUE TITLE
Election voting times are off by an hour

### ISSUE THREAD

**Issue by pshem** [DemocracyClub/WhoCanIVoteFor#801]
### Issue and Steps to Reproduce

I've imported the calendar (webcal://whocanivotefor.co.uk/elections/postcode_here.ics) into Google Calendar. The polling station opening times for the Scottish Parliament election were off by an hour - shown as 8-23, instead of the actual opening time 7-22. When I viewed the timezone reported by the calendar, it was the GMT+1.

#### Expected
The polling station opening times should match real voting location opening times (7-22).

#### Actual
The polling station opening time was shown off by an hour (8-23).

### Additional Details
* Browser and version: Imported in Firefox.
* Were you logged in?

I'm not sure if this bug is down to daylight saving time being applied on both ends (both by the calendar and by the calendar application), or something else.

**Comment by VirginiaDooley** [comment]
Thanks for this. Yes, this is related to daylight savings support with the iCal library that is currently in use. Also related to https://github.com/DemocracyClub/WhoCanIVoteFor/issues/274
