### ISSUE TITLE
Link to official documents from YNR on post pages

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/WhoCanIVoteFor#83]

**Comment by JoeMitchell** [comment]
Does this refer to party manifestos? 

Would be good to include these, e.g. http://www.thenortheastparty.org.uk/NEPManifesto2017.pdf

**Comment by michaeljcollinsuk** [comment]
@symroe not clear about this one - I can see that the SOPN document is [linked](https://github.com/DemocracyClub/WhoCanIVoteFor/blob/master/wcivf/apps/elections/templates/elections/includes/_single_ballot.html#L106) to on YNR if it exists. And can also see that there is an `import_manifestos` management command that appears to have been built for 2017? But it seems like there are displayed on the party/person page reather than post page. So I'm not sure, but my hunch is that more this issue originally implied more changes

**Comment by symroe** [comment]
I think when I made this issue I was talking about SOPNs, so in that sense it's done.

However, we do want to import local party manifestos as well. We have a management command for that, but it needs making more robust, and for the URLs it's importing from to be added to the repo.

I think that's a new issue though, and this one is done :+1:
