### ISSUE TITLE
Decide how to display candidate bios / statements.

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/WhoCanIVoteFor#85]
I checked the YNR repository, but couldn't spot the right issue for this. Related trello card here: https://trello.com/c/P4qJOx5h/973-add-biographies-profiles-statements-to-ynr

We've known for a while we want to offer candidates a space to write 'in their own words' or whatever.

I think this could be "Biography" (about you, the candidate; 100 words) and "Statement" (why do you want to be elected? what will you do? 100 words). Or it could be one box of 200 words.

This is 200 words:

Malesuada laoreet primis. A tempus ullamcorper quisque pharetra Turpis feugiat condimentum facilisis aliquam fringilla fames cum accumsan egestas cursus dapibus cras ipsum amet torquent nisl maecenas, cum laoreet pharetra. Libero vel facilisi molestie commodo lobortis nostra malesuada Dis netus blandit senectus semper blandit nec nec erat.

Placerat curae; arcu rutrum platea ultrices. Bibendum blandit imperdiet nec conubia Nibh mollis rhoncus pede sed auctor erat posuere ut. Fames sociis ullamcorper conubia aliquet gravida ligula dui morbi rhoncus. Ridiculus in mattis facilisis, iaculis placerat rutrum quam sem. Lorem. Morbi risus pulvinar est. Semper phasellus pede malesuada auctor dolor cum accumsan Nec lacus sit sociis mus proin netus nec a nascetur turpis. Etiam sed. Ad imperdiet nostra eleifend nulla integer elementum suscipit. Nec eu ante convallis eget. Turpis felis, proin lectus auctor sit erat nascetur fermentum. Aenean habitasse cursus eu sapien. Condimentum. Senectus, nullam vestibulum malesuada.

Ultrices quisque elementum pulvinar, quis mauris penatibus integer dis ullamcorper laoreet metus eros lorem vel orci gravida est nam laoreet sapien risus metus taciti, gravida at proin accumsan, est mattis netus ut penatibus ut sociosqu dolor duis, proin. Nascetur libero dictum. Lobortis mattis vestibulum lectus rutrum blandit egestas. Natoque a. Enim Justo, eleifend platea. Fringilla scelerisque Hac.

**Comment by JoeMitchell** [comment]
Crazy other form could be 'Voluntary declaration of interests' or 'Voluntary declaration of campaign spending'

**Comment by symroe** [comment]
This is done!
