### ISSUE TITLE
images on person pages are broken

### ISSUE THREAD

**Issue by mhl** [DemocracyClub/WhoCanIVoteFor#88]
e.g. on https://whocanivotefor.co.uk/person/3885/harriet-harman the `<img>` `src` is:
https://whocanivotefor.co.uk/static/media/people/photos/thttps%253A/candidates.democracyclub.org.uk/media/cache/e5/a9/e5a9aaa7dba03ec4f_oq9jiq6.jpg - whereas it should presumably be https://candidates.democracyclub.org.uk/media/cache/e5/a9/e5a9aaa7dba03ec4f_oq9jiq6.jpg (although that's a 404).

**Comment by symroe** [comment]
Fixed after the redesign
