### ISSUE TITLE
Sort out asset fingerprinting

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/WhoCanIVoteFor#92]
OMGz your website is so ugly!!

![screenshot at 2017-04-27 21 31 14](https://cloud.githubusercontent.com/assets/6025893/25503083/eae12c9e-2b90-11e7-897b-7b20854380ba.png)

### --->

that's better!

![screenshot at 2017-04-27 21 31 29](https://cloud.githubusercontent.com/assets/6025893/25503100/f524051e-2b90-11e7-87e3-cb42a8f2e1c2.png)

**Comment by davidmiller** [comment]
Same thing happened to me...

**Comment by symroe** [comment]
Assets are fingerprinted now, so this should be fixed.

**Comment by chris48s** [comment]
Is that deployed? I've intentionally kept a browser that I haven't reloaded and it still looks like the top screenshot :(

**Comment by chris48s** [comment]
Aah.. I see what is happening.. all the images and icons and stuff have fingerprints, but the key stylesheet load (`/static/css/styles.css`) isn't because it is being done in javascript

so you've got

```
    <link rel="apple-touch-icon" sizes="180x180" href="/static/dc_theme/icons/apple-touch-icon.5f52d3c8b78e.png?v=3eadRXNL3q">
    <link rel="icon" type="image/png" href="/static/dc_theme/icons/favicon-32x32.1aeb0fb2b210.png?v=3eadRXNL3q" sizes="32x32">
    <link rel="icon" type="image/png" href="/static/dc_theme/icons/favicon-16x16.b01478abae8b.png?v=3eadRXNL3q" sizes="16x16">
    <link rel="mask-icon" href="/static/dc_theme/icons/safari-pinned-tab.14b7df0226ff.svg?v=3eadRXNL3q" color="#ec008c">
    <link rel="shortcut icon" href="/static/dc_theme/icons/favicon.4921eb6574f0.ico?v=3eadRXNL3q">
```

.. all with the `?v=` param

but the stylesheet is loaded like thjs: `(['/static/css/styles.css'],document.getElementById("loadcss"))`

**Comment by symroe** [comment]
Whoops, missed that one. Should be fixed now?

**Comment by chris48s** [comment]
confirmed :+1:
