### ISSUE TITLE
Display turnout & spoilt ballot info

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/WhoCanIVoteFor#935]
We collect turnout & spoilt ballots but don't display it on WCIVF. It's been mentioned a couple of times in feedback that people would like to see this, so, maybe we should?

**Comment by VirginiaDooley** [comment]
Where are we collecting this? I am aware that it's an option to collect for results bot but I don't think we are storing it at the moment. In which case, this is: collect & display

**Comment by VirginiaDooley** [comment]
> It's blank for resultsbot, but it's an option in the manual result entry and is [included in the CSV](https://candidates.democracyclub.org.uk/uk_results/).

So it is! Where would you like this info displayed? Previous elections table?

**Comment by pmk01** [comment]
No, on the ballot page, something like this (I'll leave it to you to order/design it):

![Screenshot 2023-08-24 111531](https://github.com/DemocracyClub/WhoCanIVoteFor/assets/61510609/8d9cb6b8-888d-469b-a0b9-7542a3f872e4)

"ballots issued" = turnout (raw number). All the other numbers should be under that name in the data we collect.
