### ISSUE TITLE
Display 'profile last updated' info?

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/WhoCanIVoteFor#936]
We have a lot of out of date info on profiles, especially statements. Might we be able to date stamp profiles, or individual elements within profiles?

**Comment by pmk01** [comment]
Thinking about it, statements are probably the thing to add this to initially.

**Comment by pmk01** [comment]
Might be useful to add to candidates, too. "this statement was added over a year ago", or something. Or can we just auto-remove statements after this time???

**Comment by semiprime** [comment]
See also: https://github.com/DemocracyClub/yournextrepresentative/issues/2109

**Comment by pmk01** [comment]
From Stuart:
it seems to be wrong more often than not? a couple of examples:
https://candidates.democracyclub.org.uk/person/72914/jack-thomson
https://candidates.democracyclub.org.uk/person/19009/preet-kaur-gill
https://candidates.democracyclub.org.uk/person/20/captain-beany
https://candidates.democracyclub.org.uk/person/1412/guto-bebb

**Comment by VirginiaDooley** [comment]
> https://candidates.democracyclub.org.uk/person/72914/jack-thomson

This was fixed in YNR with https://github.com/DemocracyClub/yournextrepresentative/pull/2212. We do not have plans to expose it in WCIVF.
